// Auto-generated wizard + PDF translations — ES. Do not edit by hand.
// Source of truth: WIZ_EN in i18n-wiz.js. Regenerate if EN changes.
if (typeof TRANSLATIONS !== "undefined") {
  Object.assign(TRANSLATIONS.es, {
  "wiz.step.start": "Inicio",
  "wiz.step.owner": "Sobre ti",
  "wiz.step.property": "Inmueble",
  "wiz.step.work": "La obra",
  "wiz.step.eligibility": "Elegibilidad",
  "wiz.step.fees": "Resumen de costes",
  "wiz.step.dossier": "Dossier",
  "wiz.btn.back": "← Atrás",
  "wiz.btn.next": "Siguiente →",
  "wiz.common.yes": "Sí",
  "wiz.common.no": "No",
  "wiz.ptype.kitchen_replace": "Sustitución de cocina (misma distribución)",
  "wiz.ptype.bathroom_redo": "Reforma de baño (sin tocar muros)",
  "wiz.ptype.interior_paint": "Pintura interior / acabados",
  "wiz.ptype.facade_paint": "Pintura de fachada (sin estructural)",
  "wiz.ptype.terrace_refurb": "Renovación de terraza / patio",
  "wiz.ptype.pool_work": "Mantenimiento de piscina / alicatado",
  "wiz.ptype.windows_doors": "Sustitución de ventanas / puertas (mismos huecos)",
  "wiz.ptype.multiple": "Varias de las anteriores",
  "wiz.blocker.WALL_CHANGES": "Mover o eliminar muros requiere un proyecto visado por arquitecto. Fuera de alcance.",
  "wiz.blocker.STRUCTURAL": "Los cambios estructurales (elementos portantes, cimentaciones) requieren un proyecto completo.",
  "wiz.blocker.NEW_OPENINGS": "Los nuevos huecos en fachada requieren un proyecto visado por arquitecto.",
  "wiz.blocker.BUDGET_OVER_100K": "El presupuesto de {budget} € supera el límite de €{max} para la vía de DR simplificada.",
  "wiz.blocker.DISTRIBUTION_OVER_100M2": "Los cambios de distribución de {m2} m² superan el límite de 100 m² para la DR simplificada.",
  "wiz.blocker.HISTORIC_ZONE": "Los inmuebles en zonas históricas requieren autorización adicional de Cultura — fuera de alcance.",
  "wiz.blocker.COASTAL_ZONE": "Los inmuebles en zona costera requieren autorización de Costas — fuera de alcance para la vía simplificada.",
  "wiz.formula.demoshare": "Parte de demolición",
  "wiz.formula.rest": "Resto",
  "wiz.welcome.title": "Obtén tu licencia de reforma en Marbella en 10 minutos.",
  "wiz.welcome.subtitle": "Este asistente prepara el dossier completo que necesitas para presentar una <em>Declaración Responsable</em> ante el Ayuntamiento de Marbella. Tarda unos 10 minutos. Al final recibirás un ZIP con todos los documentos, los textos de correo a enviar y un checklist paso a paso en tu idioma.",
  "wiz.welcome.cover_title": "Qué cubrimos:",
  "wiz.welcome.cover_body": " reformas de cocina y baño (sin mover muros), pintura, obras en terraza y piscina, sustitución de ventanas y puertas. Presupuesto total inferior a €100.000. Todo lo que supere esto necesita arquitecto — te lo indicaremos en el paso de elegibilidad.",
  "wiz.welcome.nodo_title": "Qué no hacemos:",
  "wiz.welcome.nodo_body": " no presentamos en tu nombre. Tú mantienes el control. Te entregamos todo listo para enviar, con instrucciones paso a paso.",
  "wiz.welcome.start": "Empezar →",
  "wiz.owner.title": "Sobre ti",
  "wiz.owner.subtitle": "Solo lo básico para rellenar tus documentos de antemano.",
  "wiz.owner.name": "Nombre completo",
  "wiz.owner.email": "Correo electrónico",
  "wiz.owner.phone": "Teléfono (formato internacional)",
  "wiz.owner.phone_hint": "Obligatorio en el formulario oficial. Número internacional válido.",
  "wiz.owner.applying_as": "¿Presentas como…?",
  "wiz.owner.individual": "Particular",
  "wiz.owner.company": "Sociedad española (S.L. / S.A.)",
  "wiz.owner.id": "DNI / NIE / Número de pasaporte",
  "wiz.owner.id_hint": "Si eres extranjero, este es tu NIE. Los extranjeros sin NIE deben obtenerlo antes de presentar — lo explicamos en el dossier.",
  "wiz.owner.company_name": "Nombre de la empresa",
  "wiz.owner.cif": "CIF",
  "wiz.owner.err": "Por favor, introduce tu nombre y correo electrónico",
  "wiz.prop.title": "El inmueble",
  "wiz.prop.subtitle": "Dónde se realizará la obra.",
  "wiz.prop.address": "Dirección completa del inmueble",
  "wiz.prop.address_ph": "ej. Calle Almendros 14, Nueva Andalucía, Marbella",
  "wiz.prop.catastral": "Referencia catastral",
  "wiz.prop.catastral_hint": "14–20 caracteres. Encuéntrala en tu recibo del IBI o consúltala gratuitamente en",
  "wiz.prop.catastral_ph": "ej. 8765432UF3486N0001GH",
  "wiz.prop.type": "Tipo de inmueble",
  "wiz.prop.villa": "Villa / casa unifamiliar",
  "wiz.prop.townhouse": "Adosado",
  "wiz.prop.apartment": "Apartamento",
  "wiz.prop.commercial": "Local comercial / otro",
  "wiz.prop.historic_q": "¿Está el inmueble en zona histórica o protegida?",
  "wiz.prop.coastal_q": "¿Está el inmueble en zona costera (a menos de 100 m del mar)?",
  "wiz.prop.err_addr": "Por favor, introduce la dirección y la referencia catastral",
  "wiz.prop.err_cat": "La referencia catastral debe tener entre 14 y 20 caracteres",
  "wiz.work.title": "La obra",
  "wiz.work.subtitle": "Cuéntanos qué tienes previsto. Comprobaremos si encaja en la vía simplificada.",
  "wiz.work.type": "¿Qué tipo de obra?",
  "wiz.work.select": "— seleccionar —",
  "wiz.work.desc": "Descripción breve (cualquier detalle relevante)",
  "wiz.work.desc_ph": "ej. Sustitución de los muebles de cocina por nuevos con la misma distribución. Nueva encimera. Alicatado del frente.",
  "wiz.work.desc_hint": "Opcional. Lo incorporaremos a la descripción en español del formulario.",
  "wiz.work.budget": "Presupuesto de la obra (€, sin IVA)",
  "wiz.work.budget_hint": "PEM = Presupuesto de Ejecución Material. Coste de los trabajos en sí, sin IVA.",
  "wiz.work.demo": "¿Aproximadamente qué % corresponde a demolición?",
  "wiz.work.demo_hint": "Estimación aproximada. 0% si no se van a derribar muros ni superficies.",
  "wiz.work.walls_q": "¿La obra implica <strong>mover o eliminar algún muro</strong>?",
  "wiz.work.structural_q": "¿Habrá <strong>cambios estructurales</strong> (vigas, pilares, forjados)?",
  "wiz.work.openings_q": "¿Se abrirán <strong>nuevos huecos en la fachada</strong> (ventanas, puertas, balcones)?",
  "wiz.work.check_btn": "Comprobar elegibilidad →",
  "wiz.work.err": "Por favor, elige el tipo de obra e introduce un presupuesto",
  "wiz.elig.title": "Comprobación de elegibilidad",
  "wiz.elig.exempt.subtitle": "Buenas noticias: la instrucción urbanística de Marbella de enero de 2026 exime tu obra de cualquier licencia.",
  "wiz.elig.exempt.card_title": "✓ Exenta — no se necesita licencia",
  "wiz.elig.exempt.body1": "<strong>Puedes empezar la obra de inmediato.</strong> La <em>instrucción urbanística</em> de Marbella de enero de 2026 exime las obras sencillas por debajo de €10.000 (pintura, acabados, ciertas instalaciones interiores) de cualquier licencia o tasa previa, siempre que el inmueble no esté en zona protegida.",
  "wiz.elig.exempt.body2": "Podemos generarte gratuitamente un PDF de autodeclaración para tus archivos — útil en la diligencia debida de una venta futura, en disputas con vecinos o si el ayuntamiento te pregunta algún día cómo se autorizó la obra.",
  "wiz.elig.exempt.next": "Generar autodeclaración →",
  "wiz.elig.ok.subtitle": "Tu proyecto encaja en la vía de Declaración Responsable simplificada. Calculemos las tasas.",
  "wiz.elig.ok.card_title": "✓ Apto para la vía de DR simplificada",
  "wiz.elig.ok.body": "Puedes continuar sin necesidad de proyecto visado por arquitecto. Generaremos todo lo que necesitas para presentar ante el Ayuntamiento de Marbella por tu cuenta.",
  "wiz.elig.ok.next": "Ver resumen de costes →",
  "wiz.elig.no.subtitle": "Tu proyecto no encaja en la vía simplificada. Te explicamos por qué.",
  "wiz.elig.no.card_title": "✗ No apto para la vía simplificada",
  "wiz.elig.no.intro": "Los impedimentos que se indican a continuación implican que la ley española exige un proyecto visado por arquitecto (obra mayor u obra menor con visado):",
  "wiz.elig.no.whatnow": "<strong>¿Qué hago ahora?</strong> Podemos derivarte a un arquitecto partner de confianza, o puedes ajustar el alcance de tu proyecto para que encaje en la vía simplificada. Escríbenos a <a href=\"mailto:hello@marbellapermits.com\">hello@marbellapermits.com</a> para una derivación.",
  "wiz.elig.no.reset": "Reiniciar asistente",
  "wiz.elig.back": "← Atrás, ajustar el proyecto",
  "wiz.elig.reset_confirm": "¿Borrar todas tus respuestas y empezar de nuevo?",
  "wiz.fees.title": "Resumen de costes",
  "wiz.fees.subtitle": "Lo que pagarás al Ayuntamiento de Marbella, más nuestra tarifa de servicio de €99.",
  "wiz.fees.pem": "Presupuesto de la obra (PEM)",
  "wiz.fees.pem_sub": "La cifra que has declarado",
  "wiz.fees.license": "Tasa de licencia (ICIO + tasa)",
  "wiz.fees.waste": "Fianza de residuos",
  "wiz.fees.service": "Servicio de Marbella Permits",
  "wiz.fees.service_sub": "Tarifa fija, pago único",
  "wiz.fees.total_label": "Coste total de la tramitación:",
  "wiz.fees.total_body": "Las tasas del ayuntamiento ({townhall}) se abonan directamente en Marbella — las ingresas en el banco. Nuestros €99 son por preparar tu dossier completo.",
  "wiz.fees.waste_about_title": "Sobre la fianza de residuos:",
  "wiz.fees.waste_about_body": " es una fianza recuperable. Una vez terminada la obra, puedes recuperarla del ayuntamiento presentando justificante de correcta gestión de residuos.",
  "wiz.fees.generate_btn": "Generar mi dossier →",
  "wiz.dos.title": "Tu dossier está listo",
  "wiz.dos.subtitle": "Descarga el ZIP. Dentro encontrarás todo lo que necesitas para presentar, con instrucciones paso a paso en tu idioma.",
  "wiz.dos.pack_banner": "<strong>✓ El paquete contiene 6 archivos</strong> — tu libro de instrucciones paso a paso + 5 documentos que usarás a lo largo del proceso. <strong>Abre primero el archivo 00.</strong> Te indica cuándo utilizar cada uno de los demás.",
  "wiz.dos.f00": "<strong>00-START-HERE-instructions.pdf</strong> — Tu guía paso a paso. Ábrelo primero; te indica cuándo usar el resto.",
  "wiz.dos.f01": "<strong>01-form-to-sign.pdf</strong> — El formulario oficial para imprimir, firmar y escanear.",
  "wiz.dos.f02": "<strong>02-cost-breakdown.pdf</strong> — Desglose de costes en español (lo necesita el ayuntamiento).",
  "wiz.dos.f03": "<strong>03-first-email.pdf</strong> — Texto del primer correo a enviar al ayuntamiento.",
  "wiz.dos.f04": "<strong>04-second-email.pdf</strong> — Texto del segundo correo a enviar al ayuntamiento.",
  "wiz.dos.f05": "<strong>05-permission-letter-optional.pdf</strong> — Carta de autorización (solo si otra persona presenta en tu nombre).",
  "wiz.dos.download": "↓ Descargar dossier (.zip)",
  "wiz.dos.preview": "Vista previa de la DR",
  "wiz.dos.preview_title": "Vista previa — Declaración Responsable",
  "wiz.dos.next_title": "¿Qué pasa a continuación?",
  "wiz.dos.next_body": " Abre el libro de instrucciones (archivo 00). Te guía por cada correo, cada transferencia bancaria y cada carga de documentos — en orden, en tu idioma. Tiempo total de tu atención: unos 75 minutos repartidos en 2 semanas.",
  "wiz.dos.back": "← Volver al resumen de costes",
  "wiz.dos.startover": "Empezar de nuevo",
  "wiz.dos.startover_confirm": "¿Empezar de nuevo con un proyecto nuevo? Se borrarán tus respuestas actuales.",
  "wiz.dos.toast_generating": "Generando dossier…",
  "wiz.dos.toast_done": "Dossier descargado",
  "wiz.exempt.title": "Tu autodeclaración está lista",
  "wiz.exempt.subtitle": "Sin licencia. Sin tasas. Solo un breve PDF para tus archivos.",
  "wiz.exempt.pack_banner": "<strong>✓ El paquete contiene 2 archivos</strong> — un PDF de autodeclaración que cita la instrucción de Marbella de enero de 2026 que exime tu obra, y una guía breve en tu idioma sobre qué conservar.",
  "wiz.exempt.f01": "<strong>01-self-certification.pdf</strong> — Una autodeclaración formal de que tu obra está exenta conforme a la instrucción urbanística de Marbella de 2026. Fírma, fecha y guarda en tus archivos.",
  "wiz.exempt.f02": "<strong>02-what-to-keep.pdf</strong> — Guía breve: qué hacer si un vecino se queja, qué conservar para la diligencia debida en una futura venta, cuándo pasar a una DR completa (si el alcance crece).",
  "wiz.exempt.download": "↓ Descargar autodeclaración (.zip)",
  "wiz.exempt.heads_up": "<strong>Atención:</strong> la exención solo se aplica mientras la obra se mantenga dentro del alcance declarado. Si mueves muros, cambias la distribución o el presupuesto supera €10.000, necesitarás una Declaración Responsable. Vuelve al asistente y la generamos para ti.",
  "wiz.exempt.back": "← Volver a elegibilidad",
  "wiz.exempt.toast_generating": "Generando autodeclaración…",
  "wiz.exempt.toast_done": "Autodeclaración descargada",
  "pdf.cl.header": "Marbella Permits · Guía paso a paso",
  "pdf.cl.eyebrow": "Estás en el lugar correcto — empieza a leer desde aquí",
  "pdf.cl.title": "Cómo obtener tu licencia de reforma en Marbella.",
  "pdf.cl.intro": "Aquí está todo. No necesitas buscar nada más. Lee esta guía de principio a fin. Cada paso tiene su propia página y te indica qué hacer a continuación.",
  "pdf.cl.intro2": "Si algo no queda claro, llámanos o escríbenos — no lo adivines.",
  "pdf.cl.your_project": "Tu proyecto",
  "pdf.cl.tbl.property": "Inmueble",
  "pdf.cl.tbl.what": "Qué",
  "pdf.cl.tbl.cost": "Coste",
  "pdf.cl.next2weeks": "Qué ocurre en las próximas 2 semanas",
  "pdf.cl.tl1": "Hoy: imprimes y firmas un formulario (5 minutos).",
  "pdf.cl.tl2": "Hoy: envías 2 correos al ayuntamiento (5 minutos).",
  "pdf.cl.tl3": "Días 5–10: el ayuntamiento envía 2 cartas de pago. Las abonas en tu banco (15 minutos).",
  "pdf.cl.tl4": "Día 12: lo subes todo por internet y has terminado (20 minutos).",
  "pdf.cl.total_attention": "Tiempo total de TU atención: aproximadamente 1 hora. La mayor parte de las 2 semanas es simplemente esperar al ayuntamiento.",
  "pdf.cl.steps_callout_title": "Son 7 pasos. Cada uno tiene su propia página.",
  "pdf.cl.steps_callout_body": "No te saltes ninguno. No hagas los pasos fuera de orden (excepto los pasos 3+5 y 4+6, que van en paralelo — ya te lo indicaremos). Cuando termines un paso, la página te dice a qué página pasar.",
  "pdf.cl.rule_title": "Regla importante del ayuntamiento",
  "pdf.cl.rule_body": "El ayuntamiento te da UNA SOLA oportunidad para corregir errores. Si tu solicitud está incompleta y no la corriges la primera vez que te lo piden, tu expediente se archiva y tienes que empezar de cero. Por eso cada paso de esta guía incluye un pequeño checklist — no te lo saltes.",
  "pdf.cl.help": "¿Atascado? Llama al +34 690 380 502 o escribe a hello@marbellapermits.com.",
  "pdf.cl.step_of": "Paso {n} de {total}",
  "pdf.cl.find_file": "En la misma carpeta que esta guía, busca el archivo llamado:",
  "pdf.cl.find_file_folder": "En la carpeta de tu dossier, busca el archivo llamado:",
  "pdf.cl.find_file_short": "En tu carpeta, busca el archivo llamado:",
  "pdf.cl.do_in_order": "Haz estas cosas en orden:",
  "pdf.cl.done": "¿Listo?",
  "pdf.cl.s1.title": "Imprime y firma un formulario",
  "pdf.cl.s1.b1": "Abre el archivo. Imprímelo en papel normal.",
  "pdf.cl.s1.b2": "Léelo entero. La mayoría de los campos ya están rellenados (tu nombre, dirección, etc.).",
  "pdf.cl.s1.b3": "Busca la línea que pone 'Fdo.: ' cerca del final. Fírma ahí con bolígrafo.",
  "pdf.cl.s1.b4": "Escribe la fecha de hoy junto a tu firma.",
  "pdf.cl.s1.b5": "Haz una foto clara de la página firmada con tu móvil O escanéala.",
  "pdf.cl.s1.b6": "Guarda la foto o el escáner como PDF en tu ordenador. Ponle un nombre como 'formulario-firmado.pdf'.",
  "pdf.cl.s1.done": "Ahora deberías tener un PDF firmado en tu ordenador. Pasa a la página siguiente para el paso 2.",
  "pdf.cl.s2.title": "Reúne 4 documentos en una carpeta",
  "pdf.cl.s2.intro": "Crea una carpeta nueva en tu ordenador. Ponle un nombre como 'Licencia Marbella'. Mete estos 4 archivos:",
  "pdf.cl.s2.d1": "El PDF firmado que acabas de hacer en el paso 1.",
  "pdf.cl.s2.d2": "Una copia de tu pasaporte (o NIE / DNI). Una foto clara con el móvil está bien. Guárdala como PDF.",
  "pdf.cl.s2.d3": "Un plano de tu inmueble. Descárgalo gratis aquí: https://www1.sedecatastro.gob.es/ — introduce la referencia {ref}, luego haz clic en 'Consulta descriptiva y gráfica' y descarga el PDF.",
  "pdf.cl.s2.d4": "Un presupuesto de la obra. Abre el archivo 02-cost-breakdown.pdf — es una plantilla en español. Puedes usarla tal cual, o copiar el texto en Word y guardarlo como nuevo PDF.",
  "pdf.cl.s2.d_company": "Dos documentos adicionales (porque el titular es una sociedad): las escrituras de representación de la empresa y una copia del certificado del CIF (modelo 036/037).",
  "pdf.cl.s2.done": "Ahora deberías tener 4 archivos PDF (o 6 si la propiedad es de una sociedad) en una misma carpeta. Pasa a la página siguiente para el paso 3.",
  "pdf.cl.s3.title": "Envía el primer correo al ayuntamiento",
  "pdf.cl.s3.b1": "Abre el PDF. Verás el texto de un correo electrónico.",
  "pdf.cl.s3.b2": "Abre tu programa de correo (Gmail, Outlook, Apple Mail o el que uses).",
  "pdf.cl.s3.b3": "Empieza un correo nuevo.",
  "pdf.cl.s3.b4": "Copia el texto del PDF — incluidas las líneas de Para y Asunto — en tu correo.",
  "pdf.cl.s3.b5": "Adjunta los 4 archivos de tu carpeta (paso 2).",
  "pdf.cl.s3.b6": "Envía.",
  "pdf.cl.s3.wait_title": "Ahora esperas",
  "pdf.cl.s3.wait_body": "El ayuntamiento responde en 5 a 10 días hábiles. Te envían un PDF llamado 'carta de pago' — es una factura con un número de referencia que necesitarás en el paso 4. Revisa tu correo (incluida la carpeta de spam) una vez al día.",
  "pdf.cl.s3.done": "Correo enviado. Pasa a la página siguiente para el paso 4 — pero no empieces el paso 4 hasta que llegue la carta de pago a tu correo.",
  "pdf.cl.s4.title": "Paga la primera factura en tu banco",
  "pdf.cl.s4.intro": "El ayuntamiento acaba de enviarte un PDF llamado 'carta de pago'. Es una factura. Mira la esquina superior derecha — hay un número de referencia largo. Lo necesitarás.",
  "pdf.cl.amount_to_pay": "Importe a pagar:",
  "pdf.cl.s4.bank_intro": "Usa estos datos bancarios (escríbelos o cópialos con exactitud):",
  "pdf.cl.s4.bank_title": "Primera factura — datos bancarios",
  "pdf.cl.bank.name": "Nombre del banco",
  "pdf.cl.bank.account": "Número de cuenta",
  "pdf.cl.bank.intl": "Código internacional",
  "pdf.cl.bank.holder": "Titular de la cuenta",
  "pdf.cl.bank.concept": "Concepto",
  "pdf.cl.intl_note": "(solo necesario si se transfiere desde el extranjero)",
  "pdf.cl.s4.concept": "El número de referencia largo de la esquina superior derecha de la factura, luego un espacio, y: {owner}",
  "pdf.cl.s4.where_title": "Dónde pagar",
  "pdf.cl.s4.where_body": "Tienes 3 opciones. (1) Entra en la banca online de tu banco español y realiza una transferencia. (2) Acércate a cualquier sucursal de Unicaja con el PDF de la factura — ellos lo hacen por ti. (3) Desde el extranjero, pide a tu banco una transferencia SWIFT internacional usando el código indicado arriba.",
  "pdf.cl.keep_receipt_title": "Guarda el justificante",
  "pdf.cl.s4.keep_receipt_body": "Tu banco te da un justificante o confirmación. Guárdalo como PDF. Lo adjuntarás más adelante en el paso 7.",
  "pdf.cl.s4.done": "Pagado y justificante guardado. Pasa a la página siguiente para el paso 5 — puedes empezar el paso 5 incluso antes de hacer el paso 4 si quieres, el orden no importa.",
  "pdf.cl.s5.title": "Paga la fianza recuperable (esta es diferente)",
  "pdf.cl.s5.intro": "Esta es una fianza recuperable por residuos de construcción. Te la devuelven al final de la obra. En este caso, el ayuntamiento NO te envía una factura primero — tú calculas el importe y pagas, y LUEGO se lo comunicas.",
  "pdf.cl.s5.calc": "(Cómo hemos calculado esto: {formula})",
  "pdf.cl.s5.bank_intro": "Usa estos datos bancarios (banco diferente al del paso 4):",
  "pdf.cl.s5.bank_title": "Fianza recuperable — datos bancarios",
  "pdf.cl.s5.keep_receipt_body": "Guarda el justificante bancario como PDF. Lo necesitarás para el paso 6 ahora mismo, y también en el paso 7.",
  "pdf.cl.s5.done": "Pagado y justificante guardado. Pasa a la página siguiente para el paso 6.",
  "pdf.cl.s6.title": "Envía el segundo correo al ayuntamiento",
  "pdf.cl.s6.intro": "Ahora comunica al ayuntamiento que has pagado la fianza para que emitan la factura correspondiente (también llamada 'carta de pago' — misma palabra, factura diferente).",
  "pdf.cl.s6.b1": "Abre el PDF. Verás el texto de un correo electrónico.",
  "pdf.cl.s6.b2": "Copia el texto — incluidas las líneas de Para y Asunto — en un nuevo correo en tu programa de correo.",
  "pdf.cl.s6.b3": "Adjunta el justificante bancario que obtuviste en el paso 5.",
  "pdf.cl.s6.b4": "Envía.",
  "pdf.cl.s6.b5": "Espera a que el ayuntamiento responda con otra factura en PDF. Normalmente tarda 2–5 días.",
  "pdf.cl.s6.done": "Correo enviado y a la espera de su respuesta. Pasa a la página siguiente para el paso 7 — pero no empieces el paso 7 hasta que tengas en tu bandeja de entrada las dos facturas del ayuntamiento.",
  "pdf.cl.s7.title": "Sube todo a la web del ayuntamiento",
  "pdf.cl.s7.need_title": "Antes de empezar, necesitas UNA de estas opciones",
  "pdf.cl.s7.need_body": "Opción A: Un certificado digital español en tu ordenador (FNMT). Opción B: Un Cl@ve PIN vinculado a tu NIE. Opción C: Una sociedad española de la que seas titular — usa el certificado del administrador. Opción D: Alguien de confianza que tenga la opción A o B — dale la carta de autorización (archivo 05-permission-letter-optional.pdf) y pídele que haga este paso por ti. Si no tienes ninguna de estas opciones, llámanos al +34 690 380 502 y te orientamos para conseguirla.",
  "pdf.cl.s7.ready": "Cuando estés listo, sigue estos pasos uno a uno:",
  "pdf.cl.s7.b1": "Abre tu navegador web y ve a: www.marbella.es",
  "pdf.cl.s7.b2": "En la página de inicio, mira el menú superior y haz clic en 'Sede electrónica'.",
  "pdf.cl.s7.b3": "En la siguiente página, busca la sección llamada 'Trámites' (segundo recuadro de la página). Haz clic.",
  "pdf.cl.s7.b4": "Busca 'Instancia General'. Haz clic.",
  "pdf.cl.s7.b5": "Haz clic en el botón 'Acceder con Certificado Digital'.",
  "pdf.cl.s7.b6": "El navegador te pedirá que elijas un certificado. Elige el del titular del inmueble.",
  "pdf.cl.s7.b7": "Se abre un formulario. La mayoría de los campos se rellenan solos desde tu certificado. Completa el resto con los datos de tu dossier.",
  "pdf.cl.s7.dept_title": "MUY IMPORTANTE — elige el departamento correcto",
  "pdf.cl.s7.dept_body": "Hay un desplegable llamado 'Delegación'. Debes elegir LICENCIAS. NO 'urbanismo'. NO 'obras'. NO 'proyectos'. Solo LICENCIAS. Si eliges el incorrecto, tu expediente llega a la oficina equivocada y queda sin tramitar.",
  "pdf.cl.s7.attach": "Luego adjunta TODOS estos archivos (marca cada uno):",
  "pdf.cl.s7.fd1": "El formulario firmado (del paso 1)",
  "pdf.cl.s7.fd2": "El PDF del presupuesto de la obra (del paso 2)",
  "pdf.cl.s7.fd3": "El PDF del plano catastral (del paso 2)",
  "pdf.cl.s7.fd4": "Copia del pasaporte / NIE / DNI (del paso 2)",
  "pdf.cl.s7.fd5": "El justificante bancario del paso 4 (primer pago)",
  "pdf.cl.s7.fd6": "La primera carta de pago del ayuntamiento (del paso 3)",
  "pdf.cl.s7.fd7": "El justificante bancario del paso 5 (fianza)",
  "pdf.cl.s7.fd8": "La segunda carta de pago del ayuntamiento (del paso 6)",
  "pdf.cl.s7.fd_company1": "Escrituras de la sociedad (del paso 2)",
  "pdf.cl.s7.fd_company2": "Certificado del CIF de la sociedad (del paso 2)",
  "pdf.cl.s7.submit": "Haz clic en 'Presentar' al final.",
  "pdf.cl.s7.proof_title": "Guarda el justificante",
  "pdf.cl.s7.proof_body": "Tras hacer clic en Presentar, la web te muestra un pequeño PDF llamado 'acuse de recibo' o 'justificante'. Tiene un número de registro largo. GUARDA ESTE PDF. Es tu prueba legal de que has presentado la solicitud. Puedes empezar las obras en el momento en que lo veas.",
  "pdf.cl.s7.youre_done": "Eso es todo. Has terminado.",
  "pdf.cl.tr.header": "Si algo va mal",
  "pdf.cl.tr.h1": "El ayuntamiento no ha respondido a tu primer correo",
  "pdf.cl.tr.b1": "Si han pasado más de 10 días hábiles (2 semanas) desde que enviaste el correo del paso 3, responde a tu propio correo para que aparezca de nuevo al principio de su bandeja de entrada. Escribe un mensaje corto y amable en español: 'Buenos días, le escribo de nuevo para solicitar la carta de pago. Gracias.' Si sigue sin respuesta pasada otra semana, llámanos.",
  "pdf.cl.tr.h2": "El ayuntamiento te pide más documentos",
  "pdf.cl.tr.b2": "Esto se llama 'requerimiento'. Lee lo que te piden. Envía solo lo que solicitan. No discutas. No mandes documentos que no te hayan pedido. Tienes UNA sola oportunidad para subsanar — no la desperdicies.",
  "pdf.cl.tr.h3": "El ayuntamiento dice que necesitas un proyecto de arquitecto",
  "pdf.cl.tr.b3": "Esto significa que la obra es más compleja de lo que gestiona nuestro asistente. Escríbenos a hello@marbellapermits.com — te conectamos con un arquitecto partner a un precio justo.",
  "pdf.cl.tr.h4": "Elegiste la 'Delegación' incorrecta en el paso 7",
  "pdf.cl.tr.b4": "Pasa. No te agobies. Presenta una nueva instancia (vuelve a empezar el paso 7), esta vez eligiendo LICENCIAS. Adjunta una nota breve que diga 'Reemite el expediente — anterior presentado en Delegación incorrecta'. Ambas quedarán en el sistema; la incorrecta se archivará eventualmente.",
  "pdf.cl.tr.closing": "Si ocurre algo que no aparece en esta página: {help}",
  "pdf.cl.gl.header": "Términos que verás",
  "pdf.cl.gl.title": "Términos administrativos — qué significan",
  "pdf.cl.gl.intro": "El ayuntamiento utiliza términos administrativos específicos. Aquí te explicamos qué significan en lenguaje sencillo. Ten esta página a mano.",
  "pdf.cl.gl.ayuntamiento": "El organismo municipal que gestiona los trámites de licencias y obras en tu localidad.",
  "pdf.cl.gl.dr": "El formulario oficial que firmas para declarar que vas a realizar la obra. A veces se abrevia como 'DR'.",
  "pdf.cl.gl.carta_pago": "Una factura en PDF que te envía el ayuntamiento. Hay dos: una para la tasa de licencia y otra para la fianza.",
  "pdf.cl.gl.sede": "El portal online del ayuntamiento donde subes el dossier final en el paso 7.",
  "pdf.cl.gl.justificante": "El recibo que te da el banco tras realizar un pago.",
  "pdf.cl.gl.acuse": "El resguardo digital que te genera el portal online DESPUÉS de hacer clic en Presentar. Es tu prueba legal.",
  "pdf.cl.gl.fianza": "Depósito recuperable por residuos de construcción. Te lo devuelven al terminar la obra.",
  "pdf.cl.gl.presupuesto": "Desglose del coste de los trabajos, sin IVA, redactado en español.",
  "pdf.cl.gl.plano": "Un mapa de tu inmueble que se descarga gratuitamente del Catastro.",
  "pdf.cl.gl.nie": "El número de identificación de extranjero en España. Obligatorio si el titular del inmueble no es de nacionalidad española.",
  "pdf.cl.gl.subsanacion": "Corrección de errores o deficiencias en tu solicitud. Solo tienes una oportunidad.",
  "pdf.cl.gl.requerimiento": "Escrito del ayuntamiento solicitando más documentación o aclaraciones. Indica que hay que hacer una subsanación.",
  "pdf.cl.gl.tramite": "Un procedimiento administrativo. Todo el proceso de la licencia es un trámite.",
  "pdf.cl.gl.delegacion": "Departamento del ayuntamiento. Hay varios — asegúrate de elegir LICENCIAS en el paso 7.",
  "pdf.cl.gl.pem": "Coste de la obra sin IVA (la misma cifra que introdujiste en el asistente).",
  "pdf.cl.gl.icio": "El impuesto sobre construcciones y obras. Aproximadamente el 3,5% del PEM. Incluido en la primera factura.",
  "pdf.cl.gl.visado": "Sello de visado de un proyecto de arquitecto. Solo necesario para obras de mayor envergadura — no es tu caso.",
  "pdf.email.title": "Correo para copiar y enviar",
  "pdf.email.body_label": "Cuerpo — copiar literalmente",
  "pdf.email.before_title": "Antes de enviar",
  "pdf.email.before_body": "Adjunta los documentos justificativos indicados en el paso 2 del libro de instrucciones (archivo 00). Asegúrate de que todos los adjuntos sean PDFs, con nombre claro, y de menos de 10 MB cada uno.",
  "pdf.email.license_header": "03 · Primer correo — al ayuntamiento (oficinaliquidadora)",
  "pdf.email.license_instr": "Abre tu programa de correo. Pega el Para, el Asunto y el Cuerpo que aparecen a continuación. Adjunta los documentos del paso 2 del libro de instrucciones.",
  "pdf.email.waste_header": "04 · Segundo correo — al ayuntamiento (caja)",
  "pdf.email.waste_instr": "Envía este correo DESPUÉS de haber pagado la fianza recuperable (paso 5 del libro de instrucciones). Adjunta el justificante bancario.",
  "pdf.carta.when_title": "Cuándo usar esto",
  "pdf.carta.when_body": "Solo si quieres que otra persona (un administrador de fincas, gestor o abogado) presente la Declaración Responsable en tu nombre a través de la sede electrónica española. Esa persona deberá adjuntar esta carta firmada por ti.",
  "pdf.carta.brackets_title": "Los corchetes marcados son campos a rellenar",
  "pdf.carta.brackets_body": "Sustituye [Nombre del representante autorizado] y [NIE/DNI del representante] por los datos reales de la persona a quien autorizas. Imprime, firma y escanea.",
  "pdf.presu.note_title": "Nota para arquitecto / propietario",
  "pdf.presu.note_body": "Si tu expediente requiere un desglose por partidas y capítulos (movimiento de tierras, estructura, etc.), añádelo como anexo. Para obras de la Sección A, este desglose de línea única suele aceptarse.",
  "pdf.eg.header": "02 · Qué conservar en tus archivos",
  "pdf.eg.eyebrow": "Guía en tu idioma",
  "pdf.eg.title": "Tu obra está exenta. Esto es lo que debes hacer a continuación.",
  "pdf.eg.intro": "Según la instrucción urbanística de Marbella de enero de 2026, las obras sencillas por debajo de €10.000 — pintura, acabados, ciertas instalaciones interiores — no necesitan licencia. Puedes empezar mañana. Pero hay algunas cosas que conviene hacer para protegerte.",
  "pdf.eg.keep_title": "Conserva estos documentos",
  "pdf.eg.keep1": "El PDF de autodeclaración firmado (archivo 01)",
  "pdf.eg.keep2": "Una factura detallada del contratista con el importe total",
  "pdf.eg.keep3": "Fotos del antes y el después de la obra",
  "pdf.eg.keep4": "Justificantes de la gestión de residuos",
  "pdf.eg.complaint_title": "Si un vecino presenta una queja",
  "pdf.eg.complaint_body": "El ayuntamiento puede inspeccionar aunque la obra esté exenta. Si te lo solicitan, entrega: la autodeclaración (archivo 01), la factura del contratista y las fotos. La inspección confirma que la obra encaja en la categoría exenta. No se aplican sanciones si el alcance real coincide con la declaración.",
  "pdf.eg.stops_title": "Cuándo deja de aplicarse la exención",
  "pdf.eg.stops_callout_title": "Pasa a una Declaración Responsable si se cumple alguna de estas situaciones",
  "pdf.eg.stops_callout_body": "El presupuesto supera €10.000. Cualquier cambio de muros. Cualquier nuevo hueco en la fachada. Cualquier obra de fontanería o electricidad que afecte a instalaciones comunes. El inmueble está o pasa a estar en zona de protección histórica.",
  "pdf.eg.stops_body": "En cualquiera de esos casos, vuelve a marbellapermits.com y ejecuta de nuevo el asistente. Te generaremos un paquete completo de DR.",
  "pdf.eg.resale_title": "Diligencia debida en la venta",
  "pdf.eg.resale_body": "Cuando vendas el inmueble, el abogado del comprador puede preguntar si se realizaron obras de reforma y si estaban autorizadas. Entrega esta autodeclaración — demuestra que la obra estaba legalmente exenta, con la referencia del artículo correspondiente. Es exactamente lo que necesitan para cerrar la diligencia debida.",
  "pdf.eg.footer": "02 · Qué conservar en tus archivos · Marbella Permits"
});
}
