// Auto-generated wizard + PDF translations — NL. Do not edit by hand.
// Source of truth: WIZ_EN in i18n-wiz.js. Regenerate if EN changes.
if (typeof TRANSLATIONS !== "undefined") {
  Object.assign(TRANSLATIONS.nl, {
  "wiz.step.start": "Start",
  "wiz.step.owner": "Over u",
  "wiz.step.property": "Het pand",
  "wiz.step.work": "De werken",
  "wiz.step.eligibility": "Geschiktheid",
  "wiz.step.fees": "Kostenover­zicht",
  "wiz.step.dossier": "Dossier",
  "wiz.btn.back": "← Terug",
  "wiz.btn.next": "Volgende →",
  "wiz.common.yes": "Ja",
  "wiz.common.no": "Nee",
  "wiz.ptype.kitchen_replace": "Keukenvervanging (zelfde indeling)",
  "wiz.ptype.bathroom_redo": "Badkamerrenovatie (geen muurwijzigingen)",
  "wiz.ptype.interior_paint": "Binnenschilderwerk / afwerking",
  "wiz.ptype.facade_paint": "Gevelschilderwerk (niet structureel)",
  "wiz.ptype.terrace_refurb": "Terras / patio opknappen",
  "wiz.ptype.pool_work": "Zwembadonderhoud / hertegelen",
  "wiz.ptype.windows_doors": "Ramen / deuren vervangen (zelfde openingen)",
  "wiz.ptype.multiple": "Meerdere van bovenstaande",
  "wiz.blocker.WALL_CHANGES": "Het verplaatsen of verwijderen van muren vereist een gestempeld architectenproject. Buiten ons bereik.",
  "wiz.blocker.STRUCTURAL": "Structurele wijzigingen (dragende elementen, funderingen) vereisen een volledig project.",
  "wiz.blocker.NEW_OPENINGS": "Nieuwe gevelopeningen vereisen een gestempeld architectenproject.",
  "wiz.blocker.BUDGET_OVER_100K": "Projectbudget €{budget} overschrijdt het maximum van €{max} voor de eenvoudige DR.",
  "wiz.blocker.DISTRIBUTION_OVER_100M2": "Indelingswijzigingen van {m2} m² overschrijden het maximum van 100 m² voor de eenvoudige DR.",
  "wiz.blocker.HISTORIC_ZONE": "Panden in historische zones vereisen een aanvullende Cultura-machtiging — buiten ons bereik.",
  "wiz.blocker.COASTAL_ZONE": "Panden in de kustzone vereisen een Costas-machtiging — buiten het bereik van het eenvoudige traject.",
  "wiz.formula.demoshare": "Sloopandeel",
  "wiz.formula.rest": "Rest",
  "wiz.welcome.title": "Uw Marbella-renovatievergunning, in 10 minuten.",
  "wiz.welcome.subtitle": "Deze assistent stelt het volledige dossier samen dat u nodig hebt om een <em>Declaración Responsable</em> in te dienen bij het gemeentehuis van Marbella. Het duurt ongeveer 10 minuten. Aan het einde ontvangt u een ZIP met elk document, alle e-mailteksten om te versturen en een stap-voor-stap checklist in uw taal.",
  "wiz.welcome.cover_title": "Wat we dekken:",
  "wiz.welcome.cover_body": " keuken- en badkamerrenovaties (zonder muren te verplaatsen), schilderwerk, terras- en zwembadwerk, vervanging van ramen en deuren. Totaalbudget onder €100.000. Alles groter vereist een architect — dat vertellen we u bij de geschiktheidsstap.",
  "wiz.welcome.nodo_title": "Wat we niet doen:",
  "wiz.welcome.nodo_body": " wij dienen niet namens u in. U blijft zelf in de regie. Wij geven u alles kant-en-klaar, met stap-voor-stap instructies.",
  "wiz.welcome.start": "Starten →",
  "wiz.owner.title": "Over u",
  "wiz.owner.subtitle": "Alleen de basis, zodat we uw documenten kunnen voorinvullen.",
  "wiz.owner.name": "Uw volledige naam",
  "wiz.owner.email": "E-mail",
  "wiz.owner.phone": "Telefoon (internationaal formaat)",
  "wiz.owner.phone_hint": "Verplicht op het officiële formulier. Een internationaal nummer is prima.",
  "wiz.owner.applying_as": "Dient u in als…",
  "wiz.owner.individual": "Particulier",
  "wiz.owner.company": "Spaans bedrijf (S.L. / S.A.)",
  "wiz.owner.id": "DNI / NIE / Paspoortnummer",
  "wiz.owner.id_hint": "Als u buitenlander bent, is dit uw NIE. Buitenlanders zonder NIE moeten er eerst een aanvragen voordat ze kunnen indienen — we leggen dit uit in het dossier.",
  "wiz.owner.company_name": "Bedrijfsnaam",
  "wiz.owner.cif": "CIF",
  "wiz.owner.err": "Voer uw naam en e-mailadres in",
  "wiz.prop.title": "Het pand",
  "wiz.prop.subtitle": "Waar de werken plaatsvinden.",
  "wiz.prop.address": "Volledig adres van het pand",
  "wiz.prop.address_ph": "bijv. Calle Almendros 14, Nueva Andalucía, Marbella",
  "wiz.prop.catastral": "Kadastraal referentienummer",
  "wiz.prop.catastral_hint": "14–20 tekens. Zoek het op uw IBI-belastingaanslag of gratis op",
  "wiz.prop.catastral_ph": "bijv. 8765432UF3486N0001GH",
  "wiz.prop.type": "Type pand",
  "wiz.prop.villa": "Villa / vrijstaande woning",
  "wiz.prop.townhouse": "Rijtjeswoning",
  "wiz.prop.apartment": "Appartement",
  "wiz.prop.commercial": "Commercieel / overig",
  "wiz.prop.historic_q": "Ligt het pand in een historische / beschermde zone?",
  "wiz.prop.coastal_q": "Ligt het pand in de kustzone (binnen 100 m van de zee)?",
  "wiz.prop.err_addr": "Voer het adres en het kadastraal referentienummer in",
  "wiz.prop.err_cat": "Het kadastraal referentienummer moet 14–20 tekens lang zijn",
  "wiz.work.title": "De werken",
  "wiz.work.subtitle": "Vertel ons wat u van plan bent. We controleren of het past binnen het eenvoudige traject.",
  "wiz.work.type": "Wat voor werk?",
  "wiz.work.select": "— selecteer —",
  "wiz.work.desc": "Korte omschrijving (eventuele specifieke details)",
  "wiz.work.desc_ph": "bijv. Keukenkasten vervangen door nieuwe in dezelfde indeling. Nieuw werkblad. Tegelwerk van de achterwand vernieuwen.",
  "wiz.work.desc_hint": "Optioneel. We verwerken dit in de Spaanstalige omschrijving op het formulier.",
  "wiz.work.budget": "Projectbudget (€, exclusief btw)",
  "wiz.work.budget_hint": "PEM = Presupuesto de Ejecución Material. Kosten van de werken zelf, exclusief btw.",
  "wiz.work.demo": "Welk percentage betreft sloop (bij benadering)?",
  "wiz.work.demo_hint": "Ruwe schatting. 0% als er geen muren of oppervlakken worden gesloopt.",
  "wiz.work.walls_q": "Zijn er bij de werken <strong>muren die worden verplaatst of verwijderd</strong>?",
  "wiz.work.structural_q": "Zijn er <strong>structurele wijzigingen</strong> (balken, kolommen, vloeren)?",
  "wiz.work.openings_q": "Zijn er <strong>nieuwe openingen in de gevel</strong> (ramen, deuren, balkons)?",
  "wiz.work.check_btn": "Geschiktheid controleren →",
  "wiz.work.err": "Selecteer een projecttype en voer een budget in",
  "wiz.elig.title": "Geschiktheidscheck",
  "wiz.elig.exempt.subtitle": "Goed nieuws — de Marbella-instrucción urbanística van januari 2026 stelt uw werken vrij van elke vergunningsverplichting.",
  "wiz.elig.exempt.card_title": "✓ Vrijgesteld — geen vergunning nodig",
  "wiz.elig.exempt.body1": "<strong>U kunt de werken onmiddellijk legaal starten.</strong> De Marbella-<em>instrucción urbanística</em> van januari 2026 stelt eenvoudige werken onder €10.000 (schilderwerk, afwerking, bepaalde binneninstallaties) vrij van elke voorafgaande vergunning of heffing, op voorwaarde dat het pand niet in een beschermd gebied ligt.",
  "wiz.elig.exempt.body2": "We kunnen een gratis zelfverklarings-PDF genereren voor uw administratie — handig bij verkoop, burengeschillen of als het gemeentehuis ooit vraagt hoe de werken zijn vergund.",
  "wiz.elig.exempt.next": "Zelfverklaring genereren →",
  "wiz.elig.ok.subtitle": "Uw project past op het eenvoudige Declaración Responsable-traject. Laten we de kosten berekenen.",
  "wiz.elig.ok.card_title": "✓ Geschikt voor het eenvoudige DR-traject",
  "wiz.elig.ok.body": "U kunt verder zonder een gestempeld architectenproject. We genereren alles wat u nodig hebt om zelf in te dienen bij het gemeentehuis van Marbella.",
  "wiz.elig.ok.next": "Kostenoverzicht bekijken →",
  "wiz.elig.no.subtitle": "Uw project past niet op het eenvoudige traject. Dit is de reden.",
  "wiz.elig.no.card_title": "✗ Niet geschikt voor het eenvoudige traject",
  "wiz.elig.no.intro": "De onderstaande belemmeringen betekenen dat de Spaanse wet een gestempeld architectenproject vereist (obra mayor of met visum gestempelde obra menor):",
  "wiz.elig.no.whatnow": "<strong>Wat nu?</strong> We kunnen u doorverwijzen naar een geverifieerde partner-architect, of u kunt de omvang van uw project aanpassen zodat het past op het eenvoudige traject. Stuur een e-mail naar <a href=\"mailto:hello@marbellapermits.com\">hello@marbellapermits.com</a> voor een verwijzing.",
  "wiz.elig.no.reset": "Assistent opnieuw starten",
  "wiz.elig.back": "← Terug, project aanpassen",
  "wiz.elig.reset_confirm": "Al uw antwoorden wissen en opnieuw beginnen?",
  "wiz.fees.title": "Kostenoverzicht",
  "wiz.fees.subtitle": "Wat u aan het gemeentehuis van Marbella betaalt, plus onze servicevergoeding van €99.",
  "wiz.fees.pem": "Projectbudget (PEM)",
  "wiz.fees.pem_sub": "Uw opgegeven bedrag",
  "wiz.fees.license": "Vergunningsleges (ICIO + tasa)",
  "wiz.fees.waste": "Afvalwaarborg (fianza)",
  "wiz.fees.service": "Marbella Permits service",
  "wiz.fees.service_sub": "Vaste vergoeding, eenmalig betaald",
  "wiz.fees.total_label": "Totale vergunningskosten:",
  "wiz.fees.total_body": "De gemeenteheffingen ({townhall}) gaan rechtstreeks naar Marbella — u maakt ze over via de bank. Onze €99 is voor het samenstellen van uw complete dossier.",
  "wiz.fees.waste_about_title": "Over de afvalwaarborg:",
  "wiz.fees.waste_about_body": " dit is een terugbetaalbare fianza. Na afloop van de werken kunt u deze terugvorderen bij het ayuntamiento na overlegging van bewijs van correcte afvalverwerking.",
  "wiz.fees.generate_btn": "Mijn dossier genereren →",
  "wiz.dos.title": "Uw dossier is klaar",
  "wiz.dos.subtitle": "Download de ZIP. Alles wat u nodig hebt om in te dienen zit erin, met stap-voor-stap instructies in uw taal.",
  "wiz.dos.pack_banner": "<strong>✓ Pakket bevat 6 bestanden</strong> — uw stap-voor-stap instructieboekje + 5 documenten die u onderweg gebruikt. <strong>Open bestand 00 als eerste.</strong> Dit vertelt u wanneer u de andere bestanden nodig hebt.",
  "wiz.dos.f00": "<strong>00-START-HERE-instructions.pdf</strong> — Uw stap-voor-stap gids. Open dit eerst; het vertelt u wanneer u de rest gebruikt.",
  "wiz.dos.f01": "<strong>01-form-to-sign.pdf</strong> — Het officiële formulier om af te drukken, te ondertekenen en in te scannen.",
  "wiz.dos.f02": "<strong>02-cost-breakdown.pdf</strong> — Kostenoverzicht in het Spaans (het gemeentehuis heeft dit nodig).",
  "wiz.dos.f03": "<strong>03-first-email.pdf</strong> — Tekst van de eerste e-mail die u naar het gemeentehuis stuurt.",
  "wiz.dos.f04": "<strong>04-second-email.pdf</strong> — Tekst van de tweede e-mail die u naar het gemeentehuis stuurt.",
  "wiz.dos.f05": "<strong>05-permission-letter-optional.pdf</strong> — Machtigingsbrief (alleen als iemand anders namens u indient).",
  "wiz.dos.download": "↓ Dossier downloaden (.zip)",
  "wiz.dos.preview": "DR bekijken",
  "wiz.dos.preview_title": "Voorbeeld — Declaración Responsable",
  "wiz.dos.next_title": "Wat gebeurt er verder?",
  "wiz.dos.next_body": " Open het instructieboekje (bestand 00). Het leidt u door elke e-mail, elke bankoverschrijving en elke upload — op volgorde, in uw taal. Totale tijd van uw aandacht: ongeveer 75 minuten verspreid over 2 weken.",
  "wiz.dos.back": "← Terug naar kostenoverzicht",
  "wiz.dos.startover": "Opnieuw beginnen",
  "wiz.dos.startover_confirm": "Opnieuw beginnen met een nieuw project? Uw huidige antwoorden worden gewist.",
  "wiz.dos.toast_generating": "Dossier wordt gegenereerd…",
  "wiz.dos.toast_done": "Dossier gedownload",
  "wiz.exempt.title": "Uw zelfverklaring is klaar",
  "wiz.exempt.subtitle": "Geen vergunning nodig. Geen kosten. Gewoon een korte PDF voor uw administratie.",
  "wiz.exempt.pack_banner": "<strong>✓ Pakket bevat 2 bestanden</strong> — een zelfverklarings-PDF die verwijst naar de Marbella-instrucción van januari 2026 op grond waarvan uw werken zijn vrijgesteld, en een korte gids in uw taal over wat u moet bewaren.",
  "wiz.exempt.f01": "<strong>01-self-certification.pdf</strong> — Een formele zelfverklaring dat uw werken zijn vrijgesteld op grond van de Marbella instrucción urbanística 2026. Ondertekenen, dateren, bewaren.",
  "wiz.exempt.f02": "<strong>02-what-to-keep.pdf</strong> — Korte gids: wat te doen als een buur klaagt, wat te bewaren voor verkoopdossier, wanneer u moet upgraden naar een volledige DR (als de omvang groeit).",
  "wiz.exempt.download": "↓ Zelfverklaring downloaden (.zip)",
  "wiz.exempt.heads_up": "<strong>Let op:</strong> de vrijstelling geldt alleen zolang de werken binnen de opgegeven omvang blijven. Als u muren verplaatst, de indeling wijzigt of het budget boven €10.000 uitkomt, hebt u een Declaración Responsable nodig. Kom terug naar de assistent en we genereren er een voor u.",
  "wiz.exempt.back": "← Terug naar geschiktheid",
  "wiz.exempt.toast_generating": "Zelfverklaring wordt gegenereerd…",
  "wiz.exempt.toast_done": "Zelfverklaring gedownload",
  "pdf.cl.header": "Marbella Permits · Stap-voor-stap gids",
  "pdf.cl.eyebrow": "U bent op de juiste plek — begin hier te lezen",
  "pdf.cl.title": "Hoe u uw Marbella-renovatievergunning aanvraagt.",
  "pdf.cl.intro": "Dit is alles. U hoeft nergens anders te zoeken. Lees deze gids van begin tot eind. Elke stap heeft een eigen pagina en vertelt u wat u vervolgens moet doen.",
  "pdf.cl.intro2": "Als iets onduidelijk is, bel of mail ons — gok niet.",
  "pdf.cl.your_project": "Uw project",
  "pdf.cl.tbl.property": "Pand",
  "pdf.cl.tbl.what": "Wat",
  "pdf.cl.tbl.cost": "Kosten",
  "pdf.cl.next2weeks": "Wat er in de komende 2 weken gebeurt",
  "pdf.cl.tl1": "Vandaag: u drukt één formulier af en ondertekent het (5 minuten).",
  "pdf.cl.tl2": "Vandaag: u stuurt 2 e-mails naar het gemeentehuis (5 minuten).",
  "pdf.cl.tl3": "Dag 5–10: het gemeentehuis stuurt 2 rekeningen. U betaalt ze bij uw bank (15 minuten).",
  "pdf.cl.tl4": "Dag 12: u uploadt alles online en u bent klaar (20 minuten).",
  "pdf.cl.total_attention": "Totale tijd van UW aandacht: ongeveer 1 uur. Het grootste deel van de 2 weken is wachten op het gemeentehuis.",
  "pdf.cl.steps_callout_title": "Er zijn 7 stappen. Elke stap heeft een eigen pagina.",
  "pdf.cl.steps_callout_body": "Sla geen stappen over. Doe de stappen niet in de verkeerde volgorde (behalve stappen 3+5 en 4+6, die parallel lopen — dat vertellen we u). Als u een stap afrondt, vertelt de pagina u naar welke pagina u verder gaat.",
  "pdf.cl.rule_title": "Belangrijke regel van het gemeentehuis",
  "pdf.cl.rule_body": "Het gemeentehuis geeft u SLECHTS ÉÉN kans om fouten te herstellen. Als uw aanvraag onvolledig is en u herstelt dit niet de eerste keer dat ze erom vragen, wordt uw dossier gesloten en begint u opnieuw. Daarom heeft elke stap in deze gids een kleine checklist — sla ze niet over.",
  "pdf.cl.help": "Vastgelopen? Bel +34 690 380 502 of mail hello@marbellapermits.com.",
  "pdf.cl.step_of": "Stap {n} van {total}",
  "pdf.cl.find_file": "Zoek in dezelfde map als deze gids het bestand:",
  "pdf.cl.find_file_folder": "Zoek in uw dossiermap het bestand:",
  "pdf.cl.find_file_short": "Zoek in uw map het bestand:",
  "pdf.cl.do_in_order": "Doe dit in volgorde:",
  "pdf.cl.done": "Klaar?",
  "pdf.cl.s1.title": "Formulier afdrukken en ondertekenen",
  "pdf.cl.s1.b1": "Open het bestand. Druk het af op gewoon papier.",
  "pdf.cl.s1.b2": "Lees het door. De meeste velden zijn al ingevuld (uw naam, adres, enz.).",
  "pdf.cl.s1.b3": "Zoek de regel met 'Fdo.: ' onderaan. Zet daar uw handtekening met een pen.",
  "pdf.cl.s1.b4": "Schrijf de datum van vandaag naast uw handtekening.",
  "pdf.cl.s1.b5": "Maak een duidelijke foto van de ondertekende pagina met uw telefoon, OF scan hem in.",
  "pdf.cl.s1.b6": "Sla de foto of scan op als PDF op uw computer. Noem het bijvoorbeeld 'ondertekend-formulier.pdf'.",
  "pdf.cl.s1.done": "U heeft nu een ondertekende PDF op uw computer. Ga naar de volgende pagina voor stap 2.",
  "pdf.cl.s2.title": "4 documenten in één map verzamelen",
  "pdf.cl.s2.intro": "Maak een nieuwe map op uw computer. Noem die bijvoorbeeld 'Marbella vergunning'. Zet deze 4 bestanden erin:",
  "pdf.cl.s2.d1": "De ondertekende PDF die u zojuist in stap 1 hebt gemaakt.",
  "pdf.cl.s2.d2": "Een kopie van uw paspoort (of NIE / DNI). Een duidelijke foto met uw telefoon volstaat. Sla op als PDF.",
  "pdf.cl.s2.d3": "Een kaart van uw pand. Gratis te downloaden via: https://www1.sedecatastro.gob.es/ — voer referentie {ref} in, klik op 'Consulta descriptiva y gráfica' en download de PDF.",
  "pdf.cl.s2.d4": "Een kostenoverzicht. Open bestand 02-cost-breakdown.pdf — het is een sjabloon in het Spaans. U kunt het zo gebruiken, of de tekst kopiëren naar Word en opslaan als nieuwe PDF.",
  "pdf.cl.s2.d_company": "Twee extra documenten (omdat de eigenaar een bedrijf is): de escrituras de representación van het bedrijf, en een kopie van het CIF-certificaat (modelo 036/037).",
  "pdf.cl.s2.done": "U heeft nu 4 PDF-bestanden (of 6 als een bedrijf eigenaar is) in één map. Ga naar de volgende pagina voor stap 3.",
  "pdf.cl.s3.title": "De eerste e-mail naar het gemeentehuis sturen",
  "pdf.cl.s3.b1": "Open de PDF. U ziet de tekst van een e-mail.",
  "pdf.cl.s3.b2": "Open uw e-mailprogramma (Gmail, Outlook, Apple Mail, wat u gebruikt).",
  "pdf.cl.s3.b3": "Begin een nieuwe e-mail.",
  "pdf.cl.s3.b4": "Kopieer de tekst uit de PDF — inclusief de Aan- en Onderwerpregel — naar uw e-mail.",
  "pdf.cl.s3.b5": "Voeg de 4 bestanden uit uw map toe als bijlage (stap 2).",
  "pdf.cl.s3.b6": "Versturen.",
  "pdf.cl.s3.wait_title": "Nu wacht u",
  "pdf.cl.s3.wait_body": "Het gemeentehuis antwoordt binnen 5 tot 10 werkdagen. Ze sturen u een PDF genaamd 'carta de pago' — dat is een rekening met een referentienummer dat u in stap 4 nodig hebt. Controleer uw e-mail (inclusief de spam) eenmaal per dag.",
  "pdf.cl.s3.done": "E-mail verstuurd. Ga naar de volgende pagina voor stap 4 — maar begin niet met stap 4 totdat de rekening in uw inbox staat.",
  "pdf.cl.s4.title": "De eerste rekening betalen bij uw bank",
  "pdf.cl.s4.intro": "Het gemeentehuis heeft u zojuist een PDF gestuurd genaamd 'carta de pago'. Dat is een rekening. Kijk rechtsboven — daar staat een lang referentienummer. Dat hebt u nodig.",
  "pdf.cl.amount_to_pay": "Te betalen bedrag:",
  "pdf.cl.s4.bank_intro": "Gebruik deze bankgegevens (schrijf of kopieer precies):",
  "pdf.cl.s4.bank_title": "Eerste rekening — bankgegevens",
  "pdf.cl.bank.name": "Banknaam",
  "pdf.cl.bank.account": "Rekeningnummer",
  "pdf.cl.bank.intl": "Internationale code",
  "pdf.cl.bank.holder": "Rekeninghouder",
  "pdf.cl.bank.concept": "Omschrijving",
  "pdf.cl.intl_note": "(alleen nodig bij overschrijving vanuit het buitenland)",
  "pdf.cl.s4.concept": "Het lange referentienummer rechtsboven op de rekening, dan een spatie, dan: {owner}",
  "pdf.cl.s4.where_title": "Waar betalen",
  "pdf.cl.s4.where_body": "U heeft 3 opties. (1) Log in op het online bankieren van uw Spaanse bank en maak de overschrijving. (2) Ga naar een Unicaja-filiaal met de rekening-PDF — zij regelen het voor u. (3) Vanuit het buitenland vraagt u uw bank een internationale SWIFT-overschrijving te doen met de bovenstaande code.",
  "pdf.cl.keep_receipt_title": "Bewaar het betalingsbewijs",
  "pdf.cl.s4.keep_receipt_body": "Uw bank geeft u een ontvangstbewijs of bevestiging. Sla dit op als PDF. U voegt het later toe in stap 7.",
  "pdf.cl.s4.done": "Betaald en betalingsbewijs opgeslagen. Ga naar de volgende pagina voor stap 5 — u kunt stap 5 ook starten vóór stap 4 als u dat wilt, de volgorde maakt niet uit.",
  "pdf.cl.s5.title": "De terugbetaalbare waarborg betalen (deze is anders)",
  "pdf.cl.s5.intro": "Dit is een terugbetaalbare waarborg voor bouwafval. U krijgt hem terug aan het einde van de werken. Hiervoor stuurt het gemeentehuis GEEN rekening vooraf — u berekent het bedrag zelf en betaalt, en DAARNA meldt u het.",
  "pdf.cl.s5.calc": "(Zo hebben we dit berekend: {formula})",
  "pdf.cl.s5.bank_intro": "Gebruik deze bankgegevens (andere bank dan stap 4):",
  "pdf.cl.s5.bank_title": "Terugbetaalbare waarborg — bankgegevens",
  "pdf.cl.s5.keep_receipt_body": "Sla het bankbewijs op als PDF. U heeft het nu nodig voor stap 6 en opnieuw in stap 7.",
  "pdf.cl.s5.done": "Betaald en betalingsbewijs opgeslagen. Ga naar de volgende pagina voor stap 6.",
  "pdf.cl.s6.title": "De tweede e-mail naar het gemeentehuis sturen",
  "pdf.cl.s6.intro": "Informeer het gemeentehuis nu dat u de waarborg hebt betaald, zodat zij de bijbehorende rekening kunnen aanmaken (opnieuw 'carta de pago' — zelfde woord, andere rekening).",
  "pdf.cl.s6.b1": "Open de PDF. U ziet de tekst van een e-mail.",
  "pdf.cl.s6.b2": "Kopieer de tekst — inclusief de Aan- en Onderwerpregel — naar een nieuwe e-mail in uw e-mailprogramma.",
  "pdf.cl.s6.b3": "Voeg het bankbewijs van stap 5 als bijlage toe.",
  "pdf.cl.s6.b4": "Versturen.",
  "pdf.cl.s6.b5": "Wacht op het antwoord van het gemeentehuis met een nieuwe PDF-rekening. Doorgaans 2–5 dagen.",
  "pdf.cl.s6.done": "E-mail verstuurd en u wacht op hun antwoord. Ga naar de volgende pagina voor stap 7 — maar begin niet met stap 7 totdat beide gemeentehuis-rekeningen in uw inbox zijn.",
  "pdf.cl.s7.title": "Alles uploaden naar de website van het gemeentehuis",
  "pdf.cl.s7.need_title": "Voordat u begint, hebt u ÉÉN van deze opties nodig",
  "pdf.cl.s7.need_body": "Optie A: Een Spaans digitaal certificaat op uw computer (FNMT). Optie B: Een Cl@ve-PIN gekoppeld aan uw NIE. Optie C: Een Spaans bedrijf waarvan u eigenaar bent — gebruik het certificaat van de bestuurder. Optie D: Iemand die u vertrouwt en die optie A of B heeft — geef hen de machtigingsbrief (bestand 05-permission-letter-optional.pdf) en vraag hen deze stap voor u te doen. Heeft u geen van deze opties, bel ons dan op +34 690 380 502 en we begeleiden u bij het aanvragen.",
  "pdf.cl.s7.ready": "Wanneer u klaar bent, volgt u deze stappen één voor één:",
  "pdf.cl.s7.b1": "Open uw webbrowser en ga naar: www.marbella.es",
  "pdf.cl.s7.b2": "Klik op de startpagina bovenaan in het menu op 'Sede electrónica'.",
  "pdf.cl.s7.b3": "Zoek op de volgende pagina de rubriek 'Trámites' (tweede vak op de pagina). Klik erop.",
  "pdf.cl.s7.b4": "Zoek 'Instancia General'. Klik erop.",
  "pdf.cl.s7.b5": "Klik op de knop 'Acceder con Certificado Digital'.",
  "pdf.cl.s7.b6": "Uw browser vraagt u een certificaat te kiezen. Kies het certificaat van de eigenaar van het pand.",
  "pdf.cl.s7.b7": "Er opent een formulier. De meeste velden worden ingevuld vanuit uw certificaat. Vul de rest in vanuit uw dossier.",
  "pdf.cl.s7.dept_title": "HEEL BELANGRIJK — kies de juiste afdeling",
  "pdf.cl.s7.dept_body": "Er is een keuzelijst genaamd 'Delegación'. U moet LICENCIAS kiezen. NIET 'urbanismo'. NIET 'obras'. NIET 'proyectos'. Alleen LICENCIAS. Kiest u de verkeerde, dan gaat uw dossier naar het verkeerde kantoor en wordt het genegeerd.",
  "pdf.cl.s7.attach": "Voeg vervolgens AL deze bestanden toe als bijlage (vink elk af):",
  "pdf.cl.s7.fd1": "Het ondertekende formulier (uit stap 1)",
  "pdf.cl.s7.fd2": "De PDF met het kostenoverzicht (uit stap 2)",
  "pdf.cl.s7.fd3": "De kadastralekaart PDF (uit stap 2)",
  "pdf.cl.s7.fd4": "Uw kopie paspoort / NIE / DNI (uit stap 2)",
  "pdf.cl.s7.fd5": "Het bankbewijs van stap 4 (eerste betaling)",
  "pdf.cl.s7.fd6": "De eerste rekening van het gemeentehuis (uit stap 3)",
  "pdf.cl.s7.fd7": "Het bankbewijs van stap 5 (waarborg)",
  "pdf.cl.s7.fd8": "De tweede rekening van het gemeentehuis (uit stap 6)",
  "pdf.cl.s7.fd_company1": "Bedrijfs-escrituras (uit stap 2)",
  "pdf.cl.s7.fd_company2": "CIF-certificaat van het bedrijf (uit stap 2)",
  "pdf.cl.s7.submit": "Klik op 'Presentar' (Indienen) onderaan.",
  "pdf.cl.s7.proof_title": "Bewaar het bewijs",
  "pdf.cl.s7.proof_body": "Nadat u op Indienen klikt, toont de website u een kleine PDF genaamd 'acuse de recibo' of 'justificante'. Daarin staat een lang ontvangstbewijsnummer. BEWAAR DEZE PDF. Dat is uw wettelijk bewijs van indiening. U mag de werken wettelijk starten zodra u dit ontvangt.",
  "pdf.cl.s7.youre_done": "Dat is het. U bent klaar.",
  "pdf.cl.tr.header": "Als er iets misgaat",
  "pdf.cl.tr.h1": "Het gemeentehuis heeft niet geantwoord op uw eerste e-mail",
  "pdf.cl.tr.b1": "Als het meer dan 10 werkdagen (2 weken) geleden is dat u de e-mail in stap 3 verstuurd hebt, beantwoord dan uw eigen e-mail zodat die bovenaan in hun inbox verschijnt. Schrijf een kort beleefd bericht in het Spaans: 'Buenos días, le escribo de nuevo para solicitar la carta de pago. Gracias.' Als er daarna nog een week geen antwoord komt, bel ons dan.",
  "pdf.cl.tr.h2": "Het gemeentehuis vraagt om meer documenten",
  "pdf.cl.tr.b2": "Dit heet een 'requerimiento'. Lees wat ze vragen. Stuur alleen wat ze nodig hebben. Ga niet in discussie. Stuur geen extra documenten die niet gevraagd zijn. U heeft ÉÉN kans om het te herstellen — verspil die niet.",
  "pdf.cl.tr.h3": "Het gemeentehuis zegt dat u een volledig architectenproject nodig hebt",
  "pdf.cl.tr.b3": "Dit betekent dat de werken groter zijn dan onze assistent aankan. Mail ons op hello@marbellapermits.com — we koppelen u aan een partner-architect tegen een eerlijke prijs.",
  "pdf.cl.tr.h4": "U heeft de verkeerde 'Delegación' gekozen in stap 7",
  "pdf.cl.tr.b4": "Dat kan gebeuren. Geen paniek. Stuur een nieuwe instancia (begin stap 7 opnieuw) en kies deze keer LICENCIAS. Voeg een korte noot toe met de tekst 'Reemite el expediente — anterior presentado en Delegación incorrecta'. Beide staan in het systeem; de verkeerde wordt uiteindelijk afgewezen.",
  "pdf.cl.tr.closing": "Als er iets gebeurt dat niet op deze pagina staat: {help}",
  "pdf.cl.gl.header": "Woorden die u zult tegenkomen",
  "pdf.cl.gl.title": "Spaanse woorden die u zult zien — wat ze betekenen",
  "pdf.cl.gl.intro": "Het gemeentehuis gebruikt Spaanse bestuurlijke termen. Hieronder staat wat ze in gewone taal betekenen. Bewaar deze pagina bij de hand.",
  "pdf.cl.gl.ayuntamiento": "Gemeentehuis.",
  "pdf.cl.gl.dr": "Het officiële formulier dat u ondertekent om te verklaren dat u de werken gaat uitvoeren. Soms afgekort als 'DR'.",
  "pdf.cl.gl.carta_pago": "Een rekening (als PDF) die het gemeentehuis u stuurt. Er zijn er twee — één voor de vergunningsleges, één voor de waarborg.",
  "pdf.cl.gl.sede": "Het online portaal van het gemeentehuis. Hier uploadt u het definitieve dossier in stap 7.",
  "pdf.cl.gl.justificante": "Het betalingsbewijs dat uw bank u geeft na een betaling.",
  "pdf.cl.gl.acuse": "Het digitale ontvangstbewijs dat het online portaal u geeft NADAT u op Indienen klikt. Dat is uw wettelijk bewijs.",
  "pdf.cl.gl.fianza": "Terugbetaalbare waarborg voor bouwafval. U krijgt hem terug na afloop van de werken.",
  "pdf.cl.gl.presupuesto": "Kostenoverzicht van de werken, exclusief btw, in het Spaans.",
  "pdf.cl.gl.plano": "Een kaart van uw pand. Gratis te downloaden van de Spaanse kadasterwebsite.",
  "pdf.cl.gl.nie": "Het Spaanse identiteitsnummer voor buitenlanders. Verplicht als de eigenaar geen Spaans staatsburger is.",
  "pdf.cl.gl.subsanacion": "Het herstellen van fouten in uw aanvraag. U krijgt hiervoor slechts ÉÉN kans.",
  "pdf.cl.gl.requerimiento": "Een brief van het gemeentehuis waarin om meer documenten of verduidelijking wordt gevraagd. Betekent dat er subsanación nodig is.",
  "pdf.cl.gl.tramite": "Een bestuurlijke procedure. Het gehele vergunningsproces is één trámite.",
  "pdf.cl.gl.delegacion": "Afdeling van het gemeentehuis. Er zijn er meerdere — zorg dat u in stap 7 LICENCIAS kiest.",
  "pdf.cl.gl.pem": "Kosten van de werken, exclusief btw (hetzelfde bedrag dat we u in de assistent hebben gevraagd).",
  "pdf.cl.gl.icio": "De belasting op bouwwerken. Ongeveer 3,5% van de PEM. Inbegrepen in de eerste rekening.",
  "pdf.cl.gl.visado": "Een stempel van een architect op een project. Alleen nodig voor grotere werken — niet in uw geval.",
  "pdf.email.title": "E-mail om te kopiëren en te versturen",
  "pdf.email.body_label": "Tekst — kopieer woordelijk",
  "pdf.email.before_title": "Voor het versturen",
  "pdf.email.before_body": "Voeg de ondersteunende documenten uit stap 2 van het instructieboekje (bestand 00) als bijlage toe. Zorg dat alle bijlagen PDF-bestanden zijn, duidelijk benoemd en elk kleiner dan 10 MB.",
  "pdf.email.license_header": "03 · Eerste e-mail — aan het gemeentehuis (oficinaliquidadora)",
  "pdf.email.license_instr": "Open uw e-mailprogramma. Plak de Aan-, Onderwerp- en Tekstregels hieronder. Voeg de documenten uit stap 2 van het instructieboekje als bijlage toe.",
  "pdf.email.waste_header": "04 · Tweede e-mail — aan het gemeentehuis (caja)",
  "pdf.email.waste_instr": "Stuur deze e-mail NADAT u de terugbetaalbare waarborg hebt betaald (stap 5 van het instructieboekje). Voeg het bankbewijs als bijlage toe.",
  "pdf.carta.when_title": "Wanneer u dit gebruikt",
  "pdf.carta.when_body": "Alleen als u wilt dat iemand anders (een vastgoedbeheerder, gestor of advocaat) de Declaración Responsable namens u indient via de Spaanse sede electrónica. Die persoon moet deze door u ondertekende brief bijvoegen.",
  "pdf.carta.brackets_title": "Gemarkeerde haakjes zijn invulvelden",
  "pdf.carta.brackets_body": "Vervang [Nombre del representante autorizado] en [NIE/DNI del representante] door de werkelijke gegevens van de persoon die u machtigt. Afdrukken, ondertekenen, inscannen.",
  "pdf.presu.note_title": "Opmerking voor architect / eigenaar",
  "pdf.presu.note_body": "Als uw geval een uitsplitsing per partida en capítulo vereist (movimiento de tierras, estructura, enz.), voegt u dat als bijlage toe. Voor werken in Sectie A wordt deze enkelvoudige uitsplitsing doorgaans geaccepteerd.",
  "pdf.eg.header": "02 · Wat u moet bewaren",
  "pdf.eg.eyebrow": "Gids in uw taal",
  "pdf.eg.title": "Uw werken zijn vrijgesteld. Dit doet u vervolgens.",
  "pdf.eg.intro": "Op grond van de Marbella instrucción urbanística van januari 2026 hebben eenvoudige werken onder €10.000 — schilderwerk, afwerking, bepaalde binneninstallaties — geen vergunning nodig. U kunt morgen beginnen. Maar er zijn nog een paar dingen die het waard zijn om uw belangen te beschermen.",
  "pdf.eg.keep_title": "Bewaar het volgende",
  "pdf.eg.keep1": "De ondertekende zelfverklarings-PDF (bestand 01)",
  "pdf.eg.keep2": "Een gespecificeerde factuur van de aannemer met het totaalbedrag",
  "pdf.eg.keep3": "Voor- en na-foto's van de werken",
  "pdf.eg.keep4": "Bonnen van afvalverwerking",
  "pdf.eg.complaint_title": "Als een buur klaagt",
  "pdf.eg.complaint_body": "Het gemeentehuis kan ook inspecteren wanneer de werken zijn vrijgesteld. Als ze vragen stellen, geeft u hen: de zelfverklaring (bestand 01), de aannemersfactuur en de foto's. De inspectie bevestigt dat de werken binnen de vrijgestelde categorie vallen. Er zijn geen sancties zolang uw omvang overeenkomt met de verklaring.",
  "pdf.eg.stops_title": "Wanneer de vrijstelling niet meer geldt",
  "pdf.eg.stops_callout_title": "Upgrade naar een Declaración Responsable als een van deze situaties van toepassing wordt",
  "pdf.eg.stops_callout_body": "Budget groeit boven €10.000. Muurwijzigingen. Nieuwe gevelopeningen. Loodgieters- of elektriciteitswerk dat gemeenschappelijke installaties raakt. Pand is of wordt onderdeel van een historisch beschermd gebied.",
  "pdf.eg.stops_body": "Kom in dat geval terug naar marbellapermits.com en voer de assistent opnieuw uit. We stellen een volledig DR-pakket voor u op.",
  "pdf.eg.resale_title": "Due diligence bij verkoop",
  "pdf.eg.resale_body": "Als u het pand uiteindelijk verkoopt, kan de advocaat van de koper vragen of er renovatiewerken zijn uitgevoerd en of deze vergund waren. Geef hem of haar deze zelfverklaring — die toont dat de werken wettelijk vrijgesteld waren, met de wetsverwijzing. Dat is precies wat nodig is voor de due diligence.",
  "pdf.eg.footer": "02 · Wat u moet bewaren · Marbella Permits"
});
}
