// Auto-generated wizard + PDF translations — DE. Do not edit by hand.
// Source of truth: WIZ_EN in i18n-wiz.js. Regenerate if EN changes.
if (typeof TRANSLATIONS !== "undefined") {
  Object.assign(TRANSLATIONS.de, {
  "wiz.step.start": "Start",
  "wiz.step.owner": "Über Sie",
  "wiz.step.property": "Immobilie",
  "wiz.step.work": "Die Arbeiten",
  "wiz.step.eligibility": "Eignung",
  "wiz.step.fees": "Kostenübersicht",
  "wiz.step.dossier": "Dossier",
  "wiz.btn.back": "← Zurück",
  "wiz.btn.next": "Weiter →",
  "wiz.common.yes": "Ja",
  "wiz.common.no": "Nein",
  "wiz.ptype.kitchen_replace": "Küchenrenovierung (gleicher Grundriss)",
  "wiz.ptype.bathroom_redo": "Badrenovierung (keine Wandänderungen)",
  "wiz.ptype.interior_paint": "Innenanstrich / Oberflächen",
  "wiz.ptype.facade_paint": "Fassadenanstrich (nicht strukturell)",
  "wiz.ptype.terrace_refurb": "Terrassen- / Patio-Renovierung",
  "wiz.ptype.pool_work": "Poolwartung / Neufliesung",
  "wiz.ptype.windows_doors": "Fenster- / Türenaustausch (gleiche Öffnungen)",
  "wiz.ptype.multiple": "Mehrere der genannten",
  "wiz.blocker.WALL_CHANGES": "Das Versetzen oder Entfernen von Wänden erfordert ein gestempeltes Architektenprojekt. Nicht im Umfang enthalten.",
  "wiz.blocker.STRUCTURAL": "Strukturelle Änderungen (tragende Elemente, Fundamente) erfordern ein vollständiges Projekt.",
  "wiz.blocker.NEW_OPENINGS": "Neue Fassadenöffnungen erfordern ein gestempeltes Architektenprojekt.",
  "wiz.blocker.BUDGET_OVER_100K": "Projektbudget €{budget} überschreitet die Obergrenze von €{max} für die einfache Declaración Responsable.",
  "wiz.blocker.DISTRIBUTION_OVER_100M2": "Grundrissänderungen von {m2} m² überschreiten die 100-m²-Obergrenze der einfachen Declaración Responsable.",
  "wiz.blocker.HISTORIC_ZONE": "Immobilien in historischen Zonen benötigen eine zusätzliche Cultura-Genehmigung — nicht im Umfang enthalten.",
  "wiz.blocker.COASTAL_ZONE": "Immobilien in der Küstenzone benötigen eine Costas-Genehmigung — nicht im einfachen Verfahren enthalten.",
  "wiz.formula.demoshare": "Abbruchanteil",
  "wiz.formula.rest": "Rest",
  "wiz.welcome.title": "Ihre Marbella-Baugenehmigung — in 10 Minuten.",
  "wiz.welcome.subtitle": "Dieser Assistent bereitet das vollständige Dossier vor, das Sie benötigen, um eine <em>Declaración Responsable</em> beim Rathaus Marbella einzureichen. Er dauert etwa 10 Minuten. Am Ende erhalten Sie eine ZIP-Datei mit allen Dokumenten, allen E-Mail-Texten und einer Schritt-für-Schritt-Checkliste in Ihrer Sprache.",
  "wiz.welcome.cover_title": "Was wir abdecken:",
  "wiz.welcome.cover_body": " Küchen- und Badrenovierungen (ohne Wandverschiebungen), Anstriche, Terrassen- und Poolarbeiten, Fenster- und Türenaustausch. Gesamtbudget unter 100.000 €. Alles Größere erfordert einen Architekten — das teilen wir Ihnen beim Eignungsschritt mit.",
  "wiz.welcome.nodo_title": "Was wir nicht tun:",
  "wiz.welcome.nodo_body": " wir reichen nicht in Ihrem Namen ein. Sie behalten die Kontrolle. Wir übergeben Ihnen alles versandfertig, mit Schritt-für-Schritt-Anweisungen.",
  "wiz.welcome.start": "Starten →",
  "wiz.owner.title": "Über Sie",
  "wiz.owner.subtitle": "Nur die wesentlichen Angaben, damit wir Ihre Dokumente vorausfüllen können.",
  "wiz.owner.name": "Ihr vollständiger Name",
  "wiz.owner.email": "E-Mail",
  "wiz.owner.phone": "Telefon (internationales Format)",
  "wiz.owner.phone_hint": "Auf dem offiziellen Formular erforderlich. Internationale Nummern sind in Ordnung.",
  "wiz.owner.applying_as": "Sie beantragen als…",
  "wiz.owner.individual": "Privatperson",
  "wiz.owner.company": "Spanisches Unternehmen (S.L. / S.A.)",
  "wiz.owner.id": "DNI / NIE / Reisepassnummer",
  "wiz.owner.id_hint": "Wenn Sie Ausländer sind, ist das Ihre NIE. Ausländer ohne NIE müssen diese vor der Einreichung beantragen — wir erläutern das im Dossier.",
  "wiz.owner.company_name": "Firmenname",
  "wiz.owner.cif": "CIF",
  "wiz.owner.err": "Bitte geben Sie Ihren Namen und Ihre E-Mail-Adresse ein",
  "wiz.prop.title": "Die Immobilie",
  "wiz.prop.subtitle": "Wo die Arbeiten stattfinden werden.",
  "wiz.prop.address": "Vollständige Adresse der Immobilie",
  "wiz.prop.address_ph": "z. B. Calle Almendros 14, Nueva Andalucía, Marbella",
  "wiz.prop.catastral": "Katasterreferenz",
  "wiz.prop.catastral_hint": "14–20 Zeichen. Finden Sie diese auf Ihrer IBI-Steuerrechnung oder kostenlos unter",
  "wiz.prop.catastral_ph": "z. B. 8765432UF3486N0001GH",
  "wiz.prop.type": "Immobilientyp",
  "wiz.prop.villa": "Villa / freistehendes Haus",
  "wiz.prop.townhouse": "Reihenhaus",
  "wiz.prop.apartment": "Wohnung",
  "wiz.prop.commercial": "Gewerbe / Sonstiges",
  "wiz.prop.historic_q": "Liegt die Immobilie in einer historischen / geschützten Zone?",
  "wiz.prop.coastal_q": "Liegt die Immobilie in der Küstenzone (innerhalb von 100 m vom Meer)?",
  "wiz.prop.err_addr": "Bitte geben Sie Adresse und Katasterreferenz ein",
  "wiz.prop.err_cat": "Die Katasterreferenz sollte 14–20 Zeichen lang sein",
  "wiz.work.title": "Die Arbeiten",
  "wiz.work.subtitle": "Beschreiben Sie, was Sie planen. Wir prüfen, ob es in das einfache Verfahren passt.",
  "wiz.work.type": "Welche Art von Arbeiten?",
  "wiz.work.select": "— auswählen —",
  "wiz.work.desc": "Kurze Beschreibung (besondere Angaben, die erwähnenswert sind)",
  "wiz.work.desc_ph": "z. B. Austausch der Kücheneinrichtung durch neue Einheiten im gleichen Grundriss. Neue Arbeitsplatte. Neufliesung der Spritzschutzwand.",
  "wiz.work.desc_hint": "Optional. Wir werden das in die spanische Beschreibung auf dem Formular einfließen lassen.",
  "wiz.work.budget": "Projektbudget (€, ohne MwSt.)",
  "wiz.work.budget_hint": "PEM = Presupuesto de Ejecución Material. Kosten der Arbeiten selbst, ohne MwSt.",
  "wiz.work.demo": "Ungefähr wie viel % entfällt auf den Abbruch?",
  "wiz.work.demo_hint": "Grobe Schätzung. 0%, wenn keine Wände oder Oberflächen abgerissen werden.",
  "wiz.work.walls_q": "Beinhalten die Arbeiten <strong>das Versetzen oder Entfernen von Wänden</strong>?",
  "wiz.work.structural_q": "Gibt es <strong>strukturelle Änderungen</strong> (Träger, Stützen, Decken)?",
  "wiz.work.openings_q": "Gibt es <strong>neue Öffnungen in der Fassade</strong> (Fenster, Türen, Balkone)?",
  "wiz.work.check_btn": "Eignung prüfen →",
  "wiz.work.err": "Bitte wählen Sie einen Projekttyp und geben Sie ein Budget ein",
  "wiz.elig.title": "Eignungsprüfung",
  "wiz.elig.exempt.subtitle": "Gute Neuigkeit — die Marbella-Bauplanungsanweisung vom Januar 2026 befreit Ihre Arbeiten von jeglicher Genehmigungspflicht.",
  "wiz.elig.exempt.card_title": "✓ Befreit — keine Genehmigung erforderlich",
  "wiz.elig.exempt.body1": "<strong>Sie können die Arbeiten sofort rechtmäßig beginnen.</strong> Die Marbella <em>instrucción urbanística</em> vom Januar 2026 befreit einfache Arbeiten unter 10.000 € (Anstrich, Oberflächen, bestimmte Inneninstallationen) von jeder vorherigen Genehmigung oder Gebühr, sofern die Immobilie nicht in einer geschützten Zone liegt.",
  "wiz.elig.exempt.body2": "Wir können eine kostenlose Selbstzertifizierungs-PDF für Ihre Unterlagen erstellen — nützlich bei der Due-Diligence-Prüfung vor einem Verkauf, bei Nachbarschaftsstreitigkeiten oder falls das Rathaus je fragt, wie die Arbeiten genehmigt wurden.",
  "wiz.elig.exempt.next": "Selbstzertifizierung erstellen →",
  "wiz.elig.ok.subtitle": "Ihr Projekt passt in den einfachen Declaración-Responsable-Pfad. Berechnen wir nun die Gebühren.",
  "wiz.elig.ok.card_title": "✓ Geeignet für den einfachen DR-Pfad",
  "wiz.elig.ok.body": "Sie können ohne gestempeltes Architektenprojekt vorgehen. Wir erstellen alles, was Sie benötigen, um selbst beim Rathaus Marbella einzureichen.",
  "wiz.elig.ok.next": "Kostenübersicht anzeigen →",
  "wiz.elig.no.subtitle": "Ihr Projekt passt nicht in das einfache Verfahren. Hier ist der Grund.",
  "wiz.elig.no.card_title": "✗ Nicht geeignet für das einfache Verfahren",
  "wiz.elig.no.intro": "Die nachstehenden Hindernisse bedeuten, dass das spanische Recht ein gestempeltes Architektenprojekt erfordert (obra mayor oder visado-gestempelte obra menor):",
  "wiz.elig.no.whatnow": "<strong>Was nun?</strong> Wir können Sie an einen geprüften Partnerarchitekten vermitteln, oder Sie können den Umfang Ihres Projekts anpassen, damit es in das einfache Verfahren passt. Schreiben Sie an <a href=\"mailto:hello@marbellapermits.com\">hello@marbellapermits.com</a> für eine Empfehlung.",
  "wiz.elig.no.reset": "Assistent zurücksetzen",
  "wiz.elig.back": "← Zurück, Projekt anpassen",
  "wiz.elig.reset_confirm": "Alle Ihre Antworten zurücksetzen und von vorne beginnen?",
  "wiz.fees.title": "Kostenübersicht",
  "wiz.fees.subtitle": "Was Sie dem Rathaus Marbella zahlen, plus unsere 99-€-Servicegebühr.",
  "wiz.fees.pem": "Projektbudget (PEM)",
  "wiz.fees.pem_sub": "Ihre angegebene Zahl",
  "wiz.fees.license": "Lizenzgebühr (ICIO + tasa)",
  "wiz.fees.waste": "Abfallkaution (fianza)",
  "wiz.fees.service": "Marbella Permits Service",
  "wiz.fees.service_sub": "Einmalige Pauschalgebühr",
  "wiz.fees.total_label": "Gesamtkosten der Genehmigung:",
  "wiz.fees.total_body": "Die Rathausgebühren ({townhall}) gehen direkt an Marbella — Sie überweisen diese bei der Bank. Unsere 99 € sind für die Erstellung Ihres vollständigen Dossiers.",
  "wiz.fees.waste_about_title": "Zur Abfallkaution:",
  "wiz.fees.waste_about_body": " Es handelt sich um eine rückerstattbare fianza. Nach Abschluss der Arbeiten können Sie diese vom ayuntamiento gegen Nachweis einer ordnungsgemäßen Entsorgung zurückfordern.",
  "wiz.fees.generate_btn": "Mein Dossier erstellen →",
  "wiz.dos.title": "Ihr Dossier ist bereit",
  "wiz.dos.subtitle": "Laden Sie die ZIP-Datei herunter. Alles, was Sie zur Einreichung benötigen, ist darin enthalten — mit Schritt-für-Schritt-Anweisungen in Ihrer Sprache.",
  "wiz.dos.pack_banner": "<strong>✓ Paket enthält 6 Dateien</strong> — Ihr Schritt-für-Schritt-Anleitungsheft + 5 Dokumente, die Sie im Laufe des Verfahrens verwenden werden. <strong>Öffnen Sie zuerst Datei 00.</strong> Sie erklärt Ihnen, wann Sie die anderen verwenden.",
  "wiz.dos.f00": "<strong>00-START-HERE-instructions.pdf</strong> — Ihre Schritt-für-Schritt-Anleitung. Öffnen Sie diese zuerst; sie erklärt Ihnen, wann Sie die übrigen verwenden.",
  "wiz.dos.f01": "<strong>01-form-to-sign.pdf</strong> — Das offizielle Formular zum Ausdrucken, Unterschreiben und Einscannen.",
  "wiz.dos.f02": "<strong>02-cost-breakdown.pdf</strong> — Kostenaufstellung auf Spanisch (das Rathaus benötigt diese).",
  "wiz.dos.f03": "<strong>03-first-email.pdf</strong> — Text der ersten E-Mail, die an das Rathaus zu senden ist.",
  "wiz.dos.f04": "<strong>04-second-email.pdf</strong> — Text der zweiten E-Mail, die an das Rathaus zu senden ist.",
  "wiz.dos.f05": "<strong>05-permission-letter-optional.pdf</strong> — Vollmachtsschreiben (nur falls jemand anderes für Sie einreicht).",
  "wiz.dos.download": "↓ Dossier herunterladen (.zip)",
  "wiz.dos.preview": "Vorschau der DR",
  "wiz.dos.preview_title": "Vorschau — Declaración Responsable",
  "wiz.dos.next_title": "Was passiert als Nächstes?",
  "wiz.dos.next_body": " Öffnen Sie das Anleitungsheft (Datei 00). Es führt Sie durch jede E-Mail, jede Banküberweisung, jeden Upload — in der richtigen Reihenfolge, in Ihrer Sprache. Gesamtaufwand Ihrer Zeit: etwa 75 Minuten verteilt auf 2 Wochen.",
  "wiz.dos.back": "← Zurück zur Kostenübersicht",
  "wiz.dos.startover": "Von vorne beginnen",
  "wiz.dos.startover_confirm": "Mit einem neuen Projekt von vorne beginnen? Ihre aktuellen Antworten werden gelöscht.",
  "wiz.dos.toast_generating": "Dossier wird erstellt…",
  "wiz.dos.toast_done": "Dossier heruntergeladen",
  "wiz.exempt.title": "Ihre Selbstzertifizierung ist bereit",
  "wiz.exempt.subtitle": "Keine Genehmigung erforderlich. Keine Gebühr. Nur eine kurze PDF für Ihre Unterlagen.",
  "wiz.exempt.pack_banner": "<strong>✓ Paket enthält 2 Dateien</strong> — eine Selbstzertifizierungs-PDF mit Verweis auf die Marbella-Anweisung vom Januar 2026, die Ihre Arbeiten befreit, sowie eine kurze Anleitung in Ihrer Sprache, was Sie aufbewahren sollten.",
  "wiz.exempt.f01": "<strong>01-self-certification.pdf</strong> — Eine formelle Selbsterklärung, dass Ihre Arbeiten gemäß der Marbella-instrucción-urbanística von 2026 befreit sind. Unterschreiben, datieren, aufbewahren.",
  "wiz.exempt.f02": "<strong>02-what-to-keep.pdf</strong> — Kurze Anleitung: Was zu tun ist, wenn sich ein Nachbar beschwert, was Sie bei der Due-Diligence-Prüfung vor einem Verkauf aufbewahren sollten, und wann Sie auf eine vollständige DR umsteigen müssen (falls der Umfang zunimmt).",
  "wiz.exempt.download": "↓ Selbstzertifizierung herunterladen (.zip)",
  "wiz.exempt.heads_up": "<strong>Hinweis:</strong> Die Befreiung gilt nur, solange die Arbeiten im deklarierten Umfang bleiben. Wenn Sie Wände verschieben, die Raumaufteilung ändern oder das Budget über 10.000 € steigt, benötigen Sie eine Declaración Responsable. Kehren Sie zum Assistenten zurück und wir erstellen eine für Sie.",
  "wiz.exempt.back": "← Zurück zur Eignung",
  "wiz.exempt.toast_generating": "Selbstzertifizierung wird erstellt…",
  "wiz.exempt.toast_done": "Selbstzertifizierung heruntergeladen",
  "pdf.cl.header": "Marbella Permits · Schritt-für-Schritt-Anleitung",
  "pdf.cl.eyebrow": "Sie sind am richtigen Ort — beginnen Sie hier zu lesen",
  "pdf.cl.title": "So erhalten Sie Ihre Marbella-Baugenehmigung.",
  "pdf.cl.intro": "Das ist alles. Sie müssen nirgendwo anders zuerst nachsehen. Lesen Sie diese Anleitung von Anfang bis Ende. Jeder Schritt hat seine eigene Seite und erklärt Ihnen, was als Nächstes zu tun ist.",
  "pdf.cl.intro2": "Wenn etwas unklar ist, rufen Sie uns an oder schreiben Sie uns eine E-Mail — raten Sie nicht.",
  "pdf.cl.your_project": "Ihr Projekt",
  "pdf.cl.tbl.property": "Immobilie",
  "pdf.cl.tbl.what": "Was",
  "pdf.cl.tbl.cost": "Kosten",
  "pdf.cl.next2weeks": "Was in den nächsten 2 Wochen passiert",
  "pdf.cl.tl1": "Heute: Sie drucken und unterschreiben ein Formular (5 Minuten).",
  "pdf.cl.tl2": "Heute: Sie senden 2 E-Mails an das Rathaus (5 Minuten).",
  "pdf.cl.tl3": "Tage 5–10: Das Rathaus sendet 2 Rechnungen. Sie zahlen diese bei Ihrer Bank (15 Minuten).",
  "pdf.cl.tl4": "Tag 12: Sie laden alles online hoch und sind fertig (20 Minuten).",
  "pdf.cl.total_attention": "Gesamtaufwand IHRER Zeit: etwa 1 Stunde. Die meiste Zeit der 2 Wochen verbringen Sie damit, auf das Rathaus zu warten.",
  "pdf.cl.steps_callout_title": "Es gibt 7 Schritte. Jeder hat seine eigene Seite.",
  "pdf.cl.steps_callout_body": "Überspringen Sie keine Schritte. Führen Sie keine Schritte in falscher Reihenfolge aus (außer Schritte 3+5 und 4+6, die parallel laufen — wir sagen Ihnen Bescheid). Wenn Sie einen Schritt abgeschlossen haben, erklärt Ihnen die Seite, zu welcher Seite Sie als Nächstes blättern sollen.",
  "pdf.cl.rule_title": "Wichtige Regel des Rathauses",
  "pdf.cl.rule_body": "Das Rathaus gibt Ihnen NUR EINE Chance, Fehler zu korrigieren. Wenn Ihr Antrag unvollständig ist und Sie ihn beim ersten Mal nicht korrigieren, wenn sie darum bitten, wird Ihr Fall abgewiesen und Sie beginnen von vorne. Deshalb hat jeder Schritt in dieser Anleitung eine kleine Checkliste — überspringen Sie diese nicht.",
  "pdf.cl.help": "Nicht weitergekommen? Rufen Sie +34 690 380 502 an oder schreiben Sie an hello@marbellapermits.com.",
  "pdf.cl.step_of": "Schritt {n} von {total}",
  "pdf.cl.find_file": "Suchen Sie im selben Ordner wie diese Anleitung die Datei mit dem Namen:",
  "pdf.cl.find_file_folder": "Suchen Sie in Ihrem Dossier-Ordner die Datei mit dem Namen:",
  "pdf.cl.find_file_short": "Suchen Sie in Ihrem Ordner die Datei mit dem Namen:",
  "pdf.cl.do_in_order": "Führen Sie diese Schritte der Reihe nach aus:",
  "pdf.cl.done": "Fertig?",
  "pdf.cl.s1.title": "Ein Formular ausdrucken und unterschreiben",
  "pdf.cl.s1.b1": "Öffnen Sie die Datei. Drucken Sie sie auf normalem Papier aus.",
  "pdf.cl.s1.b2": "Lesen Sie es durch. Die meisten Felder sind bereits ausgefüllt (Ihr Name, Adresse usw.).",
  "pdf.cl.s1.b3": "Suchen Sie die Zeile mit 'Fdo.: ' unten auf der Seite. Unterschreiben Sie dort mit einem Stift.",
  "pdf.cl.s1.b4": "Schreiben Sie das heutige Datum neben Ihre Unterschrift.",
  "pdf.cl.s1.b5": "Machen Sie ein klares Foto der unterschriebenen Seite mit Ihrem Handy ODER scannen Sie sie ein.",
  "pdf.cl.s1.b6": "Speichern Sie das Foto oder den Scan als PDF auf Ihrem Computer. Benennen Sie die Datei zum Beispiel 'unterschriebenes-formular.pdf'.",
  "pdf.cl.s1.done": "Sie sollten nun eine unterschriebene PDF auf Ihrem Computer haben. Blättern Sie zur nächsten Seite für Schritt 2.",
  "pdf.cl.s2.title": "4 Dokumente in einem Ordner sammeln",
  "pdf.cl.s2.intro": "Erstellen Sie einen neuen Ordner auf Ihrem Computer. Nennen Sie ihn zum Beispiel 'Marbella-Genehmigung'. Legen Sie diese 4 Dateien darin ab:",
  "pdf.cl.s2.d1": "Die unterschriebene PDF, die Sie in Schritt 1 erstellt haben.",
  "pdf.cl.s2.d2": "Eine Kopie Ihres Reisepasses (oder NIE / DNI). Ein klares Foto mit Ihrem Handy ist in Ordnung. Als PDF speichern.",
  "pdf.cl.s2.d3": "Eine Karte Ihrer Immobilie. Kostenlos erhältlich unter: https://www1.sedecatastro.gob.es/ — geben Sie die Referenz {ref} ein, klicken Sie dann auf 'Consulta descriptiva y gráfica' und laden Sie die PDF herunter.",
  "pdf.cl.s2.d4": "Eine Kostenaufstellung. Öffnen Sie die Datei 02-cost-breakdown.pdf — es ist eine Vorlage auf Spanisch. Sie können sie so verwenden oder den Text in Word kopieren und als neue PDF speichern.",
  "pdf.cl.s2.d_company": "Zwei zusätzliche Dokumente (da der Eigentümer eine Gesellschaft ist): die escrituras de representación der Gesellschaft und eine Kopie des CIF-Zertifikats (modelo 036/037).",
  "pdf.cl.s2.done": "Sie sollten nun 4 PDF-Dateien (oder 6, wenn eine Gesellschaft die Immobilie besitzt) in einem Ordner haben. Blättern Sie zur nächsten Seite für Schritt 3.",
  "pdf.cl.s3.title": "Die erste E-Mail an das Rathaus senden",
  "pdf.cl.s3.b1": "Öffnen Sie die PDF. Sie sehen den Text einer E-Mail.",
  "pdf.cl.s3.b2": "Öffnen Sie Ihr E-Mail-Programm (Gmail, Outlook, Apple Mail oder was Sie verwenden).",
  "pdf.cl.s3.b3": "Starten Sie eine neue E-Mail.",
  "pdf.cl.s3.b4": "Kopieren Sie den Text aus der PDF — einschließlich der An- und Betreffzeilen — in Ihre E-Mail.",
  "pdf.cl.s3.b5": "Fügen Sie die 4 Dateien aus Ihrem Ordner bei (Schritt 2).",
  "pdf.cl.s3.b6": "Absenden.",
  "pdf.cl.s3.wait_title": "Jetzt warten Sie",
  "pdf.cl.s3.wait_body": "Das Rathaus antwortet in 5 bis 10 Werktagen. Es sendet Ihnen eine PDF namens 'carta de pago' — das ist eine Rechnung mit einer Referenznummer, die Sie in Schritt 4 benötigen. Überprüfen Sie Ihre E-Mails (einschließlich Spam-Ordner) einmal täglich.",
  "pdf.cl.s3.done": "E-Mail ist gesendet. Blättern Sie zur nächsten Seite für Schritt 4 — beginnen Sie Schritt 4 jedoch erst, wenn die Rechnung in Ihrer E-Mail angekommen ist.",
  "pdf.cl.s4.title": "Die erste Rechnung bei Ihrer Bank bezahlen",
  "pdf.cl.s4.intro": "Das Rathaus hat Ihnen gerade eine PDF namens 'carta de pago' geschickt. Das ist eine Rechnung. Schauen Sie in die obere rechte Ecke — dort steht eine lange Referenznummer. Die benötigen Sie.",
  "pdf.cl.amount_to_pay": "Zu zahlender Betrag:",
  "pdf.cl.s4.bank_intro": "Verwenden Sie diese Bankdaten (genau abschreiben oder kopieren):",
  "pdf.cl.s4.bank_title": "Erste Rechnung — Bankdaten",
  "pdf.cl.bank.name": "Bankname",
  "pdf.cl.bank.account": "Kontonummer",
  "pdf.cl.bank.intl": "Internationaler Code",
  "pdf.cl.bank.holder": "Kontoinhaber",
  "pdf.cl.bank.concept": "Verwendungszweck",
  "pdf.cl.intl_note": "(nur bei Überweisung aus dem Ausland erforderlich)",
  "pdf.cl.s4.concept": "Die lange Referenznummer aus der oberen rechten Ecke der Rechnung, dann ein Leerzeichen, dann: {owner}",
  "pdf.cl.s4.where_title": "Wo bezahlen",
  "pdf.cl.s4.where_body": "Sie haben 3 Möglichkeiten. (1) Melden Sie sich beim Online-Banking Ihrer spanischen Bank an und machen Sie eine Überweisung. (2) Gehen Sie mit der Rechnungs-PDF in eine beliebige Unicaja-Filiale — die erledigen das für Sie. (3) Aus dem Ausland bitten Sie Ihre Bank um eine internationale SWIFT-Überweisung mit dem oben genannten Code.",
  "pdf.cl.keep_receipt_title": "Beleg aufbewahren",
  "pdf.cl.s4.keep_receipt_body": "Ihre Bank gibt Ihnen eine Quittung oder Bestätigung. Speichern Sie diese als PDF. Sie werden sie später in Schritt 7 beifügen.",
  "pdf.cl.s4.done": "Bezahlt und Beleg gespeichert. Blättern Sie zur nächsten Seite für Schritt 5 — Sie können Schritt 5 auch vor Schritt 4 beginnen, wenn Sie möchten, die Reihenfolge spielt keine Rolle.",
  "pdf.cl.s5.title": "Die rückerstattbare Kaution bezahlen (diese ist anders)",
  "pdf.cl.s5.intro": "Das ist eine rückerstattbare Kaution für Bauabfall. Sie erhalten sie am Ende der Arbeiten zurück. Für diese schickt das Rathaus KEINE Rechnung vorab — Sie berechnen den Betrag selbst und zahlen, DANN benachrichtigen Sie das Rathaus.",
  "pdf.cl.s5.calc": "(So haben wir das berechnet: {formula})",
  "pdf.cl.s5.bank_intro": "Verwenden Sie diese Bankdaten (andere Bank als in Schritt 4):",
  "pdf.cl.s5.bank_title": "Rückerstattbare Kaution — Bankdaten",
  "pdf.cl.s5.keep_receipt_body": "Speichern Sie den Bankbeleg als PDF. Sie benötigen ihn für Schritt 6 sofort und noch einmal in Schritt 7.",
  "pdf.cl.s5.done": "Bezahlt und Beleg gespeichert. Blättern Sie zur nächsten Seite für Schritt 6.",
  "pdf.cl.s6.title": "Die zweite E-Mail an das Rathaus senden",
  "pdf.cl.s6.intro": "Teilen Sie dem Rathaus jetzt mit, dass Sie die Kaution bezahlt haben, damit es die entsprechende Rechnung ausstellen kann (wieder 'carta de pago' genannt — gleicher Begriff, andere Rechnung).",
  "pdf.cl.s6.b1": "Öffnen Sie die PDF. Sie sehen den Text einer E-Mail.",
  "pdf.cl.s6.b2": "Kopieren Sie den Text — einschließlich der An- und Betreffzeilen — in eine neue E-Mail in Ihrem E-Mail-Programm.",
  "pdf.cl.s6.b3": "Fügen Sie den Bankbeleg aus Schritt 5 bei.",
  "pdf.cl.s6.b4": "Absenden.",
  "pdf.cl.s6.b5": "Warten Sie auf die Antwort des Rathauses mit einer weiteren PDF-Rechnung. Üblicherweise 2–5 Tage.",
  "pdf.cl.s6.done": "E-Mail gesendet und Sie warten auf deren Antwort. Blättern Sie zur nächsten Seite für Schritt 7 — beginnen Sie Schritt 7 jedoch erst, wenn beide Rechnungen des Rathauses in Ihrem Postfach sind.",
  "pdf.cl.s7.title": "Alles auf die Rathauswebsite hochladen",
  "pdf.cl.s7.need_title": "Bevor Sie beginnen, benötigen Sie EINE dieser Optionen",
  "pdf.cl.s7.need_body": "Option A: Ein spanisches digitales Zertifikat auf Ihrem Computer (FNMT). Option B: Ein Cl@ve-PIN, der mit Ihrer NIE verknüpft ist. Option C: Eine spanische Gesellschaft, die Sie besitzen — verwenden Sie das Administradorzertifikat. Option D: Eine Person Ihres Vertrauens, die Option A oder B hat — geben Sie ihr das Vollmachtsschreiben (Datei 05-permission-letter-optional.pdf) und bitten Sie sie, diesen Schritt für Sie zu erledigen. Wenn Sie keine dieser Optionen haben, rufen Sie uns unter +34 690 380 502 an und wir erklären Ihnen, wie Sie eine erhalten.",
  "pdf.cl.s7.ready": "Wenn Sie bereit sind, führen Sie diese Schritte nacheinander aus:",
  "pdf.cl.s7.b1": "Öffnen Sie Ihren Webbrowser und gehen Sie zu: www.marbella.es",
  "pdf.cl.s7.b2": "Schauen Sie auf der Startseite in das obere Menü und klicken Sie auf 'Sede electrónica'.",
  "pdf.cl.s7.b3": "Suchen Sie auf der nächsten Seite den Abschnitt 'Trámites' (zweites Feld auf der Seite). Klicken Sie darauf.",
  "pdf.cl.s7.b4": "Suchen Sie nach 'Instancia General'. Klicken Sie darauf.",
  "pdf.cl.s7.b5": "Klicken Sie auf die Schaltfläche 'Acceder con Certificado Digital'.",
  "pdf.cl.s7.b6": "Ihr Browser wird Sie auffordern, ein Zertifikat auszuwählen. Wählen Sie das des Immobilieneigentümers.",
  "pdf.cl.s7.b7": "Ein Formular öffnet sich. Die meisten Felder werden aus Ihrem Zertifikat ausgefüllt. Füllen Sie den Rest aus Ihrem Dossier aus.",
  "pdf.cl.s7.dept_title": "SEHR WICHTIG — wählen Sie die richtige Abteilung",
  "pdf.cl.s7.dept_body": "Es gibt ein Auswahlfeld namens 'Delegación'. Sie müssen LICENCIAS wählen. NICHT 'urbanismo'. NICHT 'obras'. NICHT 'proyectos'. Nur LICENCIAS. Wenn Sie das falsche wählen, geht Ihre Akte an die falsche Stelle und wird ignoriert.",
  "pdf.cl.s7.attach": "Fügen Sie dann ALLE diese Dateien bei (haken Sie jede ab):",
  "pdf.cl.s7.fd1": "Das unterschriebene Formular (aus Schritt 1)",
  "pdf.cl.s7.fd2": "Die Kostenaufstellungs-PDF (aus Schritt 2)",
  "pdf.cl.s7.fd3": "Die Immobilienkarten-PDF (aus Schritt 2)",
  "pdf.cl.s7.fd4": "Ihre Reisepass- / NIE- / DNI-Kopie (aus Schritt 2)",
  "pdf.cl.s7.fd5": "Der Bankbeleg aus Schritt 4 (erste Zahlung)",
  "pdf.cl.s7.fd6": "Die erste Rechnung vom Rathaus (aus Schritt 3)",
  "pdf.cl.s7.fd7": "Der Bankbeleg aus Schritt 5 (Kaution)",
  "pdf.cl.s7.fd8": "Die zweite Rechnung vom Rathaus (aus Schritt 6)",
  "pdf.cl.s7.fd_company1": "Gesellschafts-escrituras (aus Schritt 2)",
  "pdf.cl.s7.fd_company2": "Gesellschafts-CIF-Zertifikat (aus Schritt 2)",
  "pdf.cl.s7.submit": "Klicken Sie unten auf 'Presentar' (Einreichen).",
  "pdf.cl.s7.proof_title": "Den Nachweis speichern",
  "pdf.cl.s7.proof_body": "Nachdem Sie auf Einreichen geklickt haben, zeigt Ihnen die Website eine kleine PDF namens 'acuse de recibo' oder 'justificante'. Diese hat eine lange Quittungsnummer darauf. SPEICHERN SIE DIESE PDF. Das ist Ihr rechtlicher Nachweis der Einreichung. Sie können die Arbeiten rechtlich beginnen, sobald Sie diese sehen.",
  "pdf.cl.s7.youre_done": "Das war es. Sie sind fertig.",
  "pdf.cl.tr.header": "Falls etwas schiefläuft",
  "pdf.cl.tr.h1": "Das Rathaus hat auf Ihre erste E-Mail nicht geantwortet",
  "pdf.cl.tr.b1": "Wenn mehr als 10 Werktage (2 Wochen) vergangen sind, seit Sie die E-Mail in Schritt 3 gesendet haben, antworten Sie auf Ihre eigene E-Mail, damit sie wieder oben in deren Posteingang erscheint. Schreiben Sie eine kurze, höfliche Nachricht auf Spanisch: 'Buenos días, le escribo de nuevo para solicitar la carta de pago. Gracias.' Wenn nach einer weiteren Woche noch keine Antwort kommt, rufen Sie uns an.",
  "pdf.cl.tr.h2": "Das Rathaus sendet eine Nachricht und bittet um weitere Dokumente",
  "pdf.cl.tr.b2": "Das nennt sich 'requerimiento'. Lesen Sie, was sie verlangen. Senden Sie nur das, was sie benötigen. Diskutieren Sie nicht. Senden Sie keine zusätzlichen Dokumente, die nicht verlangt wurden. Sie haben EINE Chance, die Dinge zu korrigieren — verschwenden Sie diese nicht.",
  "pdf.cl.tr.h3": "Das Rathaus sagt, Sie benötigen ein richtiges Architektenprojekt",
  "pdf.cl.tr.b3": "Das bedeutet, dass die Arbeiten größer sind als das, womit unser Assistent umgehen kann. Schreiben Sie uns an hello@marbellapermits.com — wir vermitteln Sie an einen Partnerarchitekten zu einem fairen Preis.",
  "pdf.cl.tr.h4": "Sie haben in Schritt 7 die falsche 'Delegación' gewählt",
  "pdf.cl.tr.b4": "Das passiert. Keine Panik. Senden Sie eine neue instancia (beginnen Sie Schritt 7 erneut), diesmal mit LICENCIAS. Fügen Sie eine kurze Notiz bei: 'Reemite el expediente — anterior presentado en Delegación incorrecta'. Beide werden im System vorhanden sein; der falsche wird schließlich abgewiesen.",
  "pdf.cl.tr.closing": "Wenn etwas passiert, das nicht auf dieser Seite steht: {help}",
  "pdf.cl.gl.header": "Begriffe, die Sie sehen werden",
  "pdf.cl.gl.title": "Spanische Begriffe, die Sie sehen werden — und ihre Bedeutung",
  "pdf.cl.gl.intro": "Das Rathaus verwendet spanische Verwaltungsbegriffe. Hier ist, was diese in einfacher Sprache bedeuten. Halten Sie diese Seite bereit.",
  "pdf.cl.gl.ayuntamiento": "Stadtverwaltung / Rathaus.",
  "pdf.cl.gl.dr": "Das offizielle Formular, das Sie unterschreiben und in dem Sie erklären, die Arbeiten durchzuführen. Manchmal als 'DR' abgekürzt.",
  "pdf.cl.gl.carta_pago": "Eine Rechnung (als PDF), die das Rathaus Ihnen schickt. Es gibt zwei — eine für die Lizenzgebühr, eine für die Kaution.",
  "pdf.cl.gl.sede": "Das Online-Portal des Rathauses. Dort laden Sie das abschließende Dossier in Schritt 7 hoch.",
  "pdf.cl.gl.justificante": "Die Quittung, die Ihre Bank Ihnen nach einer Zahlung gibt.",
  "pdf.cl.gl.acuse": "Die digitale Quittung, die Ihnen das Online-Portal gibt, NACHDEM Sie auf Einreichen geklickt haben. Das ist Ihr rechtlicher Nachweis.",
  "pdf.cl.gl.fianza": "Rückerstattbare Kaution für Bauabfall. Sie erhalten sie am Ende der Arbeiten zurück.",
  "pdf.cl.gl.presupuesto": "Kostenaufstellung der Arbeiten, ohne MwSt., auf Spanisch.",
  "pdf.cl.gl.plano": "Eine Karte Ihrer Immobilie. Sie laden diese kostenlos von der spanischen Katasterwebsite herunter.",
  "pdf.cl.gl.nie": "Die spanische Ausweisnummer für Ausländer. Erforderlich, wenn der Immobilieneigentümer kein spanischer Staatsbürger ist.",
  "pdf.cl.gl.subsanacion": "Korrektur von Fehlern in Ihrem Antrag. Sie haben nur EINE Chance.",
  "pdf.cl.gl.requerimiento": "Ein Schreiben des Rathauses mit der Bitte um weitere Dokumente oder Klärungen. Bedeutet, dass eine subsanación erforderlich ist.",
  "pdf.cl.gl.tramite": "Ein Verwaltungsvorgang. Das gesamte Genehmigungsverfahren ist ein trámite.",
  "pdf.cl.gl.delegacion": "Abteilung des Rathauses. Es gibt viele — achten Sie darauf, in Schritt 7 LICENCIAS auszuwählen.",
  "pdf.cl.gl.pem": "Kosten der Arbeiten, ohne MwSt. (die gleiche Zahl, die wir Sie im Assistenten gefragt haben).",
  "pdf.cl.gl.icio": "Die Steuer auf Bauarbeiten. Etwa 3,5% des PEM. In der ersten Rechnung enthalten.",
  "pdf.cl.gl.visado": "Ein Stempel auf einem Architektenprojekt. Nur für größere Arbeiten erforderlich — nicht Ihr Fall.",
  "pdf.email.title": "E-Mail zum Kopieren und Senden",
  "pdf.email.body_label": "Text — wörtlich kopieren",
  "pdf.email.before_title": "Vor dem Senden",
  "pdf.email.before_body": "Fügen Sie die Begleitdokumente bei, die in Schritt 2 des Anleitungshefts (Datei 00) aufgeführt sind. Stellen Sie sicher, dass alle Anhänge PDFs sind, klar benannt und jeweils unter 10 MB groß.",
  "pdf.email.license_header": "03 · Erste E-Mail — an das Rathaus (oficinaliquidadora)",
  "pdf.email.license_instr": "Öffnen Sie Ihr E-Mail-Programm. Fügen Sie An, Betreff und Text unten ein. Fügen Sie die Dokumente aus Schritt 2 des Anleitungshefts bei.",
  "pdf.email.waste_header": "04 · Zweite E-Mail — an das Rathaus (caja)",
  "pdf.email.waste_instr": "Senden Sie diese NACHDEM Sie die rückerstattbare Kaution bezahlt haben (Schritt 5 des Anleitungshefts). Fügen Sie den Bankbeleg bei.",
  "pdf.carta.when_title": "Wann Sie das verwenden",
  "pdf.carta.when_body": "Nur wenn Sie möchten, dass jemand anderes (ein Hausverwalter, Gestor oder Anwalt) die Declaración Responsable in Ihrem Namen über die spanische sede electrónica einreicht. Die betreffende Person muss dieses von Ihnen unterschriebene Schreiben beifügen.",
  "pdf.carta.brackets_title": "Hervorgehobene Klammern sind Platzhalter",
  "pdf.carta.brackets_body": "Ersetzen Sie [Nombre del representante autorizado] und [NIE/DNI del representante] durch die tatsächlichen Angaben der Person, die Sie bevollmächtigen. Ausdrucken, unterschreiben, einscannen.",
  "pdf.presu.note_title": "Hinweis für Architekten / Eigentümer",
  "pdf.presu.note_body": "Wenn Ihr Fall eine Aufgliederung nach Gewerken (movimiento de tierras, estructura usw.) erfordert, fügen Sie diese als Anhang hinzu. Für Arbeiten der Kategorie A wird diese einzeilige Aufgliederung in der Regel akzeptiert.",
  "pdf.eg.header": "02 · Was aufzubewahren ist",
  "pdf.eg.eyebrow": "Anleitung in Ihrer Sprache",
  "pdf.eg.title": "Ihre Arbeiten sind befreit. So geht es weiter.",
  "pdf.eg.intro": "Gemäß der Marbella-instrucción-urbanística vom Januar 2026 benötigen einfache Arbeiten unter 10.000 € — Anstrich, Oberflächen, bestimmte Inneninstallationen — keine Genehmigung. Sie können morgen beginnen. Es gibt jedoch noch ein paar Dinge, die es wert sind, zu tun, um sich zu schützen.",
  "pdf.eg.keep_title": "Bewahren Sie diese Unterlagen auf",
  "pdf.eg.keep1": "Die unterschriebene Selbstzertifizierungs-PDF (Datei 01)",
  "pdf.eg.keep2": "Eine aufgeschlüsselte Rechnung des Handwerkers mit den Gesamtkosten",
  "pdf.eg.keep3": "Vorher- / Nachher-Fotos der Arbeiten",
  "pdf.eg.keep4": "Quittungen für die Entsorgung von Bauabfall",
  "pdf.eg.complaint_title": "Falls sich ein Nachbar beschwert",
  "pdf.eg.complaint_body": "Das Rathaus kann auch dann eine Inspektion durchführen, wenn die Arbeiten befreit sind. Wenn es fragt, übergeben Sie: die Selbstzertifizierung (Datei 01), die Handwerkerrechnung und die Fotos. Die Inspektion bestätigt, dass die Arbeiten in die befreite Kategorie fallen. Es werden keine Strafen verhängt, wenn Ihr Umfang der Erklärung entspricht.",
  "pdf.eg.stops_title": "Wann die Befreiung nicht mehr gilt",
  "pdf.eg.stops_callout_title": "Wechseln Sie zu einer Declaración Responsable, wenn einer dieser Punkte zutrifft",
  "pdf.eg.stops_callout_body": "Budget übersteigt 10.000 €. Irgendwelche Wandänderungen. Neue Öffnungen in der Fassade. Sanitär- oder Elektroarbeiten, die gemeinschaftliche Installationen betreffen. Die Immobilie liegt in einem oder wird Teil eines historisch geschützten Bereichs.",
  "pdf.eg.stops_body": "Kehren Sie in jedem dieser Fälle zu marbellapermits.com zurück und starten Sie den Assistenten erneut. Wir erstellen ein vollständiges DR-Paket für Sie.",
  "pdf.eg.resale_title": "Due-Diligence-Prüfung beim Verkauf",
  "pdf.eg.resale_body": "Wenn Sie die Immobilie irgendwann verkaufen, kann der Anwalt des Käufers fragen, ob Renovierungsarbeiten durchgeführt wurden und ob diese genehmigt waren. Übergeben Sie ihm diese Selbstzertifizierung — sie zeigt, dass die Arbeiten rechtlich befreit waren, mit dem Artikelverweis. Genau das brauchen sie für die Due-Diligence-Prüfung.",
  "pdf.eg.footer": "02 · Was aufzubewahren ist · Marbella Permits"
});
}
