// Auto-generated wizard + PDF translations — FR. Do not edit by hand.
// Source of truth: WIZ_EN in i18n-wiz.js. Regenerate if EN changes.
if (typeof TRANSLATIONS !== "undefined") {
  Object.assign(TRANSLATIONS.fr, {
  "wiz.step.start": "Démarrer",
  "wiz.step.owner": "Vos informations",
  "wiz.step.property": "Le bien",
  "wiz.step.work": "Les travaux",
  "wiz.step.eligibility": "Éligibilité",
  "wiz.step.fees": "Récapitulatif des coûts",
  "wiz.step.dossier": "Dossier",
  "wiz.btn.back": "← Retour",
  "wiz.btn.next": "Suivant →",
  "wiz.common.yes": "Oui",
  "wiz.common.no": "Non",
  "wiz.ptype.kitchen_replace": "Remplacement de cuisine (même configuration)",
  "wiz.ptype.bathroom_redo": "Rénovation de salle de bain (sans déplacer de mur)",
  "wiz.ptype.interior_paint": "Peinture intérieure / finitions",
  "wiz.ptype.facade_paint": "Peinture de façade (non structurel)",
  "wiz.ptype.terrace_refurb": "Rénovation de terrasse / patio",
  "wiz.ptype.pool_work": "Entretien de piscine / carrelage",
  "wiz.ptype.windows_doors": "Remplacement de fenêtres / portes (mêmes ouvertures)",
  "wiz.ptype.multiple": "Plusieurs des options ci-dessus",
  "wiz.blocker.WALL_CHANGES": "Déplacer ou supprimer des murs nécessite un projet d'architecte visé. Hors périmètre.",
  "wiz.blocker.STRUCTURAL": "Les modifications structurelles (éléments porteurs, fondations) exigent un projet complet.",
  "wiz.blocker.NEW_OPENINGS": "Les nouvelles ouvertures de façade requièrent un projet d'architecte visé.",
  "wiz.blocker.BUDGET_OVER_100K": "Le budget du projet €{budget} dépasse le plafond DR simple de €{max}.",
  "wiz.blocker.DISTRIBUTION_OVER_100M2": "Les modifications de distribution de {m2} m² dépassent le plafond DR simple de 100 m².",
  "wiz.blocker.HISTORIC_ZONE": "Les biens en zone historique nécessitent une autorisation supplémentaire de Cultura — hors périmètre.",
  "wiz.blocker.COASTAL_ZONE": "Les biens en zone côtière nécessitent une autorisation Costas — hors périmètre pour la voie simple.",
  "wiz.formula.demoshare": "Part démolition",
  "wiz.formula.rest": "Reste",
  "wiz.welcome.title": "Obtenez votre permis de rénovation à Marbella, en 10 minutes.",
  "wiz.welcome.subtitle": "Cet assistant prépare le dossier complet pour déposer une <em>Declaración Responsable</em> auprès de la mairie de Marbella. Comptez environ 10 minutes. À la fin, vous recevrez un ZIP contenant chaque document, chaque texte de courriel à envoyer, et une checklist pas à pas dans votre langue.",
  "wiz.welcome.cover_title": "Ce que nous couvrons :",
  "wiz.welcome.cover_body": " rénovations de cuisines et salles de bain (sans déplacer de murs), peinture, travaux de terrasse et de piscine, remplacement de fenêtres et portes. Budget total inférieur à €100 000. Au-delà, un architecte est nécessaire — nous vous l'indiquerons à l'étape d'éligibilité.",
  "wiz.welcome.nodo_title": "Ce que nous ne faisons pas :",
  "wiz.welcome.nodo_body": " nous ne déposons pas à votre place. Vous restez aux commandes. Nous vous remettons tout, prêt à envoyer, avec des instructions pas à pas.",
  "wiz.welcome.start": "Démarrer →",
  "wiz.owner.title": "Vos informations",
  "wiz.owner.subtitle": "Juste l'essentiel pour pré-remplir vos documents.",
  "wiz.owner.name": "Votre nom complet",
  "wiz.owner.email": "Email",
  "wiz.owner.phone": "Téléphone (format international)",
  "wiz.owner.phone_hint": "Obligatoire sur le formulaire officiel. Un numéro international est accepté.",
  "wiz.owner.applying_as": "Vous déposez en tant que…",
  "wiz.owner.individual": "Particulier",
  "wiz.owner.company": "Société espagnole (S.L. / S.A.)",
  "wiz.owner.id": "Numéro DNI / NIE / Passeport",
  "wiz.owner.id_hint": "Si vous êtes étranger, il s'agit de votre NIE. Les étrangers sans NIE doivent en obtenir un avant de déposer — nous l'expliquerons dans le dossier.",
  "wiz.owner.company_name": "Nom de la société",
  "wiz.owner.cif": "CIF",
  "wiz.owner.err": "Veuillez saisir votre nom et votre email",
  "wiz.prop.title": "Le bien",
  "wiz.prop.subtitle": "L'endroit où se dérouleront les travaux.",
  "wiz.prop.address": "Adresse complète du bien",
  "wiz.prop.address_ph": "ex. Calle Almendros 14, Nueva Andalucía, Marbella",
  "wiz.prop.catastral": "Référence cadastrale",
  "wiz.prop.catastral_hint": "14 à 20 caractères. Vous la trouverez sur votre avis de taxe IBI, ou gratuitement à l'adresse",
  "wiz.prop.catastral_ph": "ex. 8765432UF3486N0001GH",
  "wiz.prop.type": "Type de bien",
  "wiz.prop.villa": "Villa / maison individuelle",
  "wiz.prop.townhouse": "Maison de ville",
  "wiz.prop.apartment": "Appartement",
  "wiz.prop.commercial": "Commercial / autre",
  "wiz.prop.historic_q": "Le bien est-il situé dans une zone historique / protégée ?",
  "wiz.prop.coastal_q": "Le bien est-il en zone côtière (à moins de 100 m de la mer) ?",
  "wiz.prop.err_addr": "Veuillez saisir l'adresse et la référence cadastrale",
  "wiz.prop.err_cat": "La référence cadastrale doit comporter 14 à 20 caractères",
  "wiz.work.title": "Les travaux",
  "wiz.work.subtitle": "Décrivez ce que vous prévoyez. Nous vérifierons si cela entre dans la voie simple.",
  "wiz.work.type": "Quel type de travaux ?",
  "wiz.work.select": "— sélectionner —",
  "wiz.work.desc": "Description succincte (tout détail utile à préciser)",
  "wiz.work.desc_ph": "ex. Remplacement des meubles de cuisine avec une nouvelle configuration identique. Nouveau plan de travail. Nouveau carrelage du crédence.",
  "wiz.work.desc_hint": "Facultatif. Nous l'intégrerons à la description espagnole sur le formulaire.",
  "wiz.work.budget": "Budget du projet (€, hors TVA)",
  "wiz.work.budget_hint": "PEM = Presupuesto de Ejecución Material. Coût des travaux eux-mêmes, hors TVA.",
  "wiz.work.demo": "Quelle est la part approximative de démolition (%) ?",
  "wiz.work.demo_hint": "Estimation approximative. 0% si aucun mur ni aucune surface ne sera démoli.",
  "wiz.work.walls_q": "Les travaux impliquent-ils de <strong>déplacer ou supprimer des murs</strong> ?",
  "wiz.work.structural_q": "Y a-t-il des <strong>modifications structurelles</strong> (poutres, colonnes, planchers) ?",
  "wiz.work.openings_q": "Y a-t-il de <strong>nouvelles ouvertures dans la façade</strong> (fenêtres, portes, balcons) ?",
  "wiz.work.check_btn": "Vérifier l'éligibilité →",
  "wiz.work.err": "Veuillez sélectionner un type de projet et saisir un budget",
  "wiz.elig.title": "Vérification d'éligibilité",
  "wiz.elig.exempt.subtitle": "Bonne nouvelle — l'instruction urbanistique de Marbella de janvier 2026 exempte vos travaux de toute obligation de permis.",
  "wiz.elig.exempt.card_title": "✓ Exempté — aucun permis requis",
  "wiz.elig.exempt.body1": "<strong>Vous pouvez légalement commencer les travaux immédiatement.</strong> L'<em>instrucción urbanística</em> de Marbella de janvier 2026 exempte les travaux simples de moins de €10 000 (peinture, finitions, certaines installations intérieures) de tout permis ou taxe préalable, à condition que le bien ne soit pas en zone protégée.",
  "wiz.elig.exempt.body2": "Nous pouvons générer un PDF d'auto-certification gratuit pour vos archives — utile lors de la revente, en cas de litige avec un voisin, ou si la mairie vous demande un jour comment les travaux ont été autorisés.",
  "wiz.elig.exempt.next": "Générer l'auto-certification →",
  "wiz.elig.ok.subtitle": "Votre projet entre dans la voie Declaración Responsable simple. Calculons les taxes.",
  "wiz.elig.ok.card_title": "✓ Éligible à la voie DR simple",
  "wiz.elig.ok.body": "Vous pouvez avancer sans projet d'architecte visé. Nous générerons tout ce qu'il vous faut pour déposer vous-même auprès de la mairie de Marbella.",
  "wiz.elig.ok.next": "Voir le récapitulatif des coûts →",
  "wiz.elig.no.subtitle": "Votre projet n'entre pas dans la voie simple. Voici pourquoi.",
  "wiz.elig.no.card_title": "✗ Non éligible à la voie simple",
  "wiz.elig.no.intro": "Les blocages ci-dessous signifient que la loi espagnole exige un projet d'architecte visé (obra mayor ou obra menor avec visa) :",
  "wiz.elig.no.whatnow": "<strong>Que faire maintenant ?</strong> Nous pouvons vous mettre en relation avec un architecte partenaire vérifié, ou vous pouvez ajuster le périmètre de votre projet pour qu'il entre dans la voie simple. Écrivez à <a href=\"mailto:hello@marbellapermits.com\">hello@marbellapermits.com</a> pour une mise en relation.",
  "wiz.elig.no.reset": "Réinitialiser l'assistant",
  "wiz.elig.back": "← Retour, modifier le projet",
  "wiz.elig.reset_confirm": "Effacer toutes vos réponses et recommencer ?",
  "wiz.fees.title": "Récapitulatif des coûts",
  "wiz.fees.subtitle": "Ce que vous paierez à la mairie de Marbella, plus nos €99 de frais de service.",
  "wiz.fees.pem": "Budget du projet (PEM)",
  "wiz.fees.pem_sub": "Le montant que vous avez déclaré",
  "wiz.fees.license": "Taxe de licence (ICIO + tasa)",
  "wiz.fees.waste": "Caution déchets (fianza)",
  "wiz.fees.service": "Service Marbella Permits",
  "wiz.fees.service_sub": "Forfait unique",
  "wiz.fees.total_label": "Coût total de la procédure :",
  "wiz.fees.total_body": "Les taxes municipales ({townhall}) sont versées directement à Marbella — vous les payez à votre banque. Nos €99 couvrent la préparation de votre dossier complet.",
  "wiz.fees.waste_about_title": "À propos de la caution déchets :",
  "wiz.fees.waste_about_body": " il s'agit d'une fianza remboursable. Une fois les travaux terminés, vous pouvez la récupérer auprès de l'ayuntamiento sur présentation d'une preuve d'élimination correcte des déchets.",
  "wiz.fees.generate_btn": "Générer mon dossier →",
  "wiz.dos.title": "Votre dossier est prêt",
  "wiz.dos.subtitle": "Téléchargez le ZIP. Tout ce qu'il vous faut pour déposer est à l'intérieur, avec des instructions pas à pas dans votre langue.",
  "wiz.dos.pack_banner": "<strong>✓ Le pack contient 6 fichiers</strong> — votre guide d'instructions pas à pas + 5 documents que vous utiliserez au fil des étapes. <strong>Ouvrez le fichier 00 en premier.</strong> Il vous indique quand utiliser les autres.",
  "wiz.dos.f00": "<strong>00-START-HERE-instructions.pdf</strong> — Votre guide pas à pas. Ouvrez-le en premier ; il vous indique quand utiliser les autres.",
  "wiz.dos.f01": "<strong>01-form-to-sign.pdf</strong> — Le formulaire officiel à imprimer, signer et scanner.",
  "wiz.dos.f02": "<strong>02-cost-breakdown.pdf</strong> — Récapitulatif des coûts en espagnol (la mairie en a besoin).",
  "wiz.dos.f03": "<strong>03-first-email.pdf</strong> — Texte du premier courriel à envoyer à la mairie.",
  "wiz.dos.f04": "<strong>04-second-email.pdf</strong> — Texte du deuxième courriel à envoyer à la mairie.",
  "wiz.dos.f05": "<strong>05-permission-letter-optional.pdf</strong> — Lettre d'autorisation (uniquement si quelqu'un d'autre dépose à votre place).",
  "wiz.dos.download": "↓ Télécharger le dossier (.zip)",
  "wiz.dos.preview": "Aperçu de la DR",
  "wiz.dos.preview_title": "Aperçu — Declaración Responsable",
  "wiz.dos.next_title": "Et ensuite ?",
  "wiz.dos.next_body": " Ouvrez le guide d'instructions (fichier 00). Il vous accompagne pour chaque courriel, chaque virement bancaire, chaque téléversement — dans l'ordre, dans votre langue. Temps total de votre part : environ 75 minutes réparties sur 2 semaines.",
  "wiz.dos.back": "← Retour au récapitulatif des coûts",
  "wiz.dos.startover": "Recommencer",
  "wiz.dos.startover_confirm": "Recommencer avec un nouveau projet ? Vos réponses actuelles seront effacées.",
  "wiz.dos.toast_generating": "Génération du dossier…",
  "wiz.dos.toast_done": "Dossier téléchargé",
  "wiz.exempt.title": "Votre auto-certification est prête",
  "wiz.exempt.subtitle": "Aucun permis requis. Aucun frais. Juste un court PDF pour vos archives.",
  "wiz.exempt.pack_banner": "<strong>✓ Le pack contient 2 fichiers</strong> — un PDF d'auto-certification citant l'instruction de Marbella de janvier 2026 qui exempte vos travaux, et un court guide dans votre langue expliquant ce qu'il faut conserver.",
  "wiz.exempt.f01": "<strong>01-self-certification.pdf</strong> — Une auto-déclaration formelle attestant que vos travaux sont exemptés au titre de l'instrucción urbanística de Marbella de 2026. Signez, datez, conservez.",
  "wiz.exempt.f02": "<strong>02-what-to-keep.pdf</strong> — Court guide : que faire si un voisin se plaint, que conserver pour la diligence raisonnable lors de la revente, et quand passer à une DR complète (si le périmètre s'élargit).",
  "wiz.exempt.download": "↓ Télécharger l'auto-certification (.zip)",
  "wiz.exempt.heads_up": "<strong>Attention :</strong> l'exemption ne s'applique que si les travaux restent dans le périmètre déclaré. Si vous déplacez des murs, modifiez la distribution ou si le budget dépasse €10 000, vous aurez besoin d'une Declaración Responsable. Revenez à l'assistant et nous en générerons une.",
  "wiz.exempt.back": "← Retour à l'éligibilité",
  "wiz.exempt.toast_generating": "Génération de l'auto-certification…",
  "wiz.exempt.toast_done": "Auto-certification téléchargée",
  "pdf.cl.header": "Marbella Permits · Guide pas à pas",
  "pdf.cl.eyebrow": "Vous êtes au bon endroit — commencez à lire ici",
  "pdf.cl.title": "Comment obtenir votre permis de rénovation à Marbella.",
  "pdf.cl.intro": "Tout est ici. Vous n'avez besoin de consulter nulle part ailleurs en premier. Lisez ce guide du début à la fin. Chaque étape a sa propre page et vous indique ce qu'il faut faire ensuite.",
  "pdf.cl.intro2": "Si quelque chose n'est pas clair, appelez-nous ou envoyez-nous un courriel — ne devinez pas.",
  "pdf.cl.your_project": "Votre projet",
  "pdf.cl.tbl.property": "Bien",
  "pdf.cl.tbl.what": "Nature des travaux",
  "pdf.cl.tbl.cost": "Coût",
  "pdf.cl.next2weeks": "Ce qui se passe dans les 2 prochaines semaines",
  "pdf.cl.tl1": "Aujourd'hui : vous imprimez et signez un formulaire (5 minutes).",
  "pdf.cl.tl2": "Aujourd'hui : vous envoyez 2 courriels à la mairie (5 minutes).",
  "pdf.cl.tl3": "Jours 5 à 10 : la mairie envoie 2 avis de paiement. Vous les réglez à votre banque (15 minutes).",
  "pdf.cl.tl4": "Jour 12 : vous téléversez tout en ligne et c'est terminé (20 minutes).",
  "pdf.cl.total_attention": "Temps total de VOTRE attention : environ 1 heure. La majeure partie des 2 semaines consiste à attendre la mairie.",
  "pdf.cl.steps_callout_title": "Il y a 7 étapes. Chacune a sa propre page.",
  "pdf.cl.steps_callout_body": "Ne sautez pas d'étapes. Ne les faites pas dans le désordre (sauf les étapes 3+5 et 4+6, qui se déroulent en parallèle — nous vous le préciserons). Quand vous terminez une étape, la page vous indique sur quelle page passer ensuite.",
  "pdf.cl.rule_title": "Règle importante de la mairie",
  "pdf.cl.rule_body": "La mairie ne vous accorde QU'UNE SEULE chance de corriger les erreurs. Si votre dossier est incomplet et que vous ne le corrigez pas la première fois qu'elle vous le demande, votre dossier est rejeté et vous recommencez à zéro. C'est pourquoi chaque étape de ce guide comporte une petite checklist — ne la sautez pas.",
  "pdf.cl.help": "Bloqué(e) ? Appelez le +34 690 380 502 ou écrivez à hello@marbellapermits.com.",
  "pdf.cl.step_of": "Étape {n} sur {total}",
  "pdf.cl.find_file": "Dans le même dossier que ce guide, trouvez le fichier intitulé :",
  "pdf.cl.find_file_folder": "Dans votre dossier de dossier, trouvez le fichier intitulé :",
  "pdf.cl.find_file_short": "Dans votre dossier, trouvez le fichier intitulé :",
  "pdf.cl.do_in_order": "Effectuez ces actions dans l'ordre :",
  "pdf.cl.done": "Terminé ?",
  "pdf.cl.s1.title": "Imprimez et signez un formulaire",
  "pdf.cl.s1.b1": "Ouvrez le fichier. Imprimez-le sur du papier ordinaire.",
  "pdf.cl.s1.b2": "Lisez-le en entier. La plupart des champs sont déjà remplis (votre nom, adresse, etc.).",
  "pdf.cl.s1.b3": "Trouvez la ligne 'Fdo.: ' près du bas. Signez-y à l'encre.",
  "pdf.cl.s1.b4": "Inscrivez la date du jour à côté de votre signature.",
  "pdf.cl.s1.b5": "Prenez une photo nette de la page signée avec votre téléphone, OU scannez-la.",
  "pdf.cl.s1.b6": "Enregistrez la photo ou le scan au format PDF sur votre ordinateur. Nommez-le par exemple 'formulaire-signe.pdf'.",
  "pdf.cl.s1.done": "Vous devriez maintenant avoir un PDF signé sur votre ordinateur. Passez à la page suivante pour l'étape 2.",
  "pdf.cl.s2.title": "Rassemblez 4 documents dans un dossier",
  "pdf.cl.s2.intro": "Créez un nouveau dossier sur votre ordinateur. Appelez-le par exemple 'Permis Marbella'. Placez-y ces 4 fichiers :",
  "pdf.cl.s2.d1": "Le PDF signé que vous venez de créer à l'étape 1.",
  "pdf.cl.s2.d2": "Une copie de votre passeport (ou NIE / DNI). Une photo nette prise avec votre téléphone convient. Enregistrez en PDF.",
  "pdf.cl.s2.d3": "Un plan de votre bien. Obtenez-le gratuitement ici : https://www1.sedecatastro.gob.es/ — saisissez la référence {ref}, puis cliquez sur 'Consulta descriptiva y gráfica' et téléchargez le PDF.",
  "pdf.cl.s2.d4": "Un récapitulatif des coûts. Ouvrez le fichier 02-cost-breakdown.pdf — c'est un modèle en espagnol. Vous pouvez l'utiliser tel quel, ou copier le texte dans Word et enregistrer en nouveau PDF.",
  "pdf.cl.s2.d_company": "Deux documents supplémentaires (car le propriétaire est une société) : les escrituras de representación de la société, et une copie du certificat CIF (modelo 036/037).",
  "pdf.cl.s2.done": "Vous devriez maintenant avoir 4 fichiers PDF (ou 6 si une société est propriétaire du bien) dans un dossier. Passez à la page suivante pour l'étape 3.",
  "pdf.cl.s3.title": "Envoyez le premier courriel à la mairie",
  "pdf.cl.s3.b1": "Ouvrez le PDF. Vous y verrez le texte d'un courriel.",
  "pdf.cl.s3.b2": "Ouvrez votre programme de messagerie (Gmail, Outlook, Apple Mail, ou autre).",
  "pdf.cl.s3.b3": "Rédigez un nouveau courriel.",
  "pdf.cl.s3.b4": "Copiez le texte du PDF — y compris les lignes À et Objet — dans votre courriel.",
  "pdf.cl.s3.b5": "Joignez les 4 fichiers de votre dossier (étape 2).",
  "pdf.cl.s3.b6": "Envoyez.",
  "pdf.cl.s3.wait_title": "Maintenant, vous attendez",
  "pdf.cl.s3.wait_body": "La mairie répond sous 5 à 10 jours ouvrables. Elle vous envoie un PDF appelé 'carta de pago' — c'est une facture avec un numéro de référence dont vous aurez besoin à l'étape 4. Vérifiez vos courriels (y compris le dossier spam) une fois par jour.",
  "pdf.cl.s3.done": "Le courriel est envoyé. Passez à la page suivante pour l'étape 4 — mais ne commencez l'étape 4 que lorsque la facture arrive dans votre messagerie.",
  "pdf.cl.s4.title": "Payez la première facture à votre banque",
  "pdf.cl.s4.intro": "La mairie vient de vous envoyer un PDF appelé 'carta de pago'. C'est une facture. Regardez le coin supérieur droit — il y a un long numéro de référence. Vous en aurez besoin.",
  "pdf.cl.amount_to_pay": "Montant à payer :",
  "pdf.cl.s4.bank_intro": "Utilisez ces coordonnées bancaires (recopiez-les ou copiez-les exactement) :",
  "pdf.cl.s4.bank_title": "Première facture — coordonnées bancaires",
  "pdf.cl.bank.name": "Nom de la banque",
  "pdf.cl.bank.account": "Numéro de compte",
  "pdf.cl.bank.intl": "Code international",
  "pdf.cl.bank.holder": "Titulaire du compte",
  "pdf.cl.bank.concept": "Référence",
  "pdf.cl.intl_note": "(uniquement si vous virez depuis l'étranger)",
  "pdf.cl.s4.concept": "Le long numéro de référence figurant en haut à droite de la facture, suivi d'un espace, puis : {owner}",
  "pdf.cl.s4.where_title": "Comment payer",
  "pdf.cl.s4.where_body": "Vous avez 3 options. (1) Connectez-vous à la banque en ligne de votre banque espagnole et effectuez un virement. (2) Rendez-vous dans n'importe quelle agence Unicaja avec le PDF de la facture — ils le feront pour vous. (3) Depuis l'étranger, demandez à votre banque un virement SWIFT international en utilisant le code ci-dessus.",
  "pdf.cl.keep_receipt_title": "Conservez le reçu",
  "pdf.cl.s4.keep_receipt_body": "Votre banque vous remet un reçu ou une confirmation. Enregistrez-le en PDF. Vous le joindrez plus tard à l'étape 7.",
  "pdf.cl.s4.done": "Payé et reçu enregistré. Passez à la page suivante pour l'étape 5 — vous pouvez commencer l'étape 5 avant même d'effectuer l'étape 4 si vous le souhaitez, l'ordre n'a pas d'importance.",
  "pdf.cl.s5.title": "Payez la caution remboursable (celle-ci est différente)",
  "pdf.cl.s5.intro": "Il s'agit d'une caution remboursable pour les déchets de chantier. Vous la récupérez à la fin des travaux. Pour celle-ci, la mairie n'envoie PAS de facture au préalable — vous calculez le montant vous-même et vous payez, PUIS vous les en informez.",
  "pdf.cl.s5.calc": "(Comment nous avons calculé ce montant : {formula})",
  "pdf.cl.s5.bank_intro": "Utilisez ces coordonnées bancaires (banque différente de l'étape 4) :",
  "pdf.cl.s5.bank_title": "Caution remboursable — coordonnées bancaires",
  "pdf.cl.s5.keep_receipt_body": "Enregistrez le reçu bancaire en PDF. Vous en aurez besoin pour l'étape 6 tout de suite, et à nouveau à l'étape 7.",
  "pdf.cl.s5.done": "Payé et reçu enregistré. Passez à la page suivante pour l'étape 6.",
  "pdf.cl.s6.title": "Envoyez le deuxième courriel à la mairie",
  "pdf.cl.s6.intro": "Informez maintenant la mairie que vous avez payé la caution afin qu'elle puisse émettre la facture correspondante (appelée à nouveau 'carta de pago' — même mot, facture différente).",
  "pdf.cl.s6.b1": "Ouvrez le PDF. Vous y verrez le texte d'un courriel.",
  "pdf.cl.s6.b2": "Copiez le texte — y compris les lignes À et Objet — dans un nouveau courriel dans votre programme de messagerie.",
  "pdf.cl.s6.b3": "Joignez le reçu bancaire obtenu à l'étape 5.",
  "pdf.cl.s6.b4": "Envoyez.",
  "pdf.cl.s6.b5": "Attendez la réponse de la mairie avec une nouvelle facture en PDF. Généralement 2 à 5 jours.",
  "pdf.cl.s6.done": "Courriel envoyé et vous attendez leur réponse. Passez à la page suivante pour l'étape 7 — mais ne commencez l'étape 7 que lorsque les deux factures de la mairie sont dans votre messagerie.",
  "pdf.cl.s7.title": "Téléversez tout sur le site de la mairie",
  "pdf.cl.s7.need_title": "Avant de commencer, vous avez besoin de L'UN de ces éléments",
  "pdf.cl.s7.need_body": "Option A : un certificat numérique espagnol sur votre ordinateur (FNMT). Option B : un code PIN Cl@ve lié à votre NIE. Option C : une société espagnole dont vous êtes propriétaire — utilisez le certificat de l'administrateur. Option D : une personne de confiance disposant de l'option A ou B — remettez-lui la lettre d'autorisation (fichier 05-permission-letter-optional.pdf) et demandez-lui d'effectuer cette étape à votre place. Si vous ne disposez d'aucune de ces options, appelez-nous au +34 690 380 502 et nous vous guiderons pour en obtenir une.",
  "pdf.cl.s7.ready": "Lorsque vous êtes prêt(e), suivez ces étapes une par une :",
  "pdf.cl.s7.b1": "Ouvrez votre navigateur web et accédez à : www.marbella.es",
  "pdf.cl.s7.b2": "Sur la page d'accueil, regardez le menu en haut et cliquez sur 'Sede electrónica'.",
  "pdf.cl.s7.b3": "Sur la page suivante, trouvez la section 'Trámites' (deuxième encadré de la page). Cliquez dessus.",
  "pdf.cl.s7.b4": "Cherchez 'Instancia General'. Cliquez dessus.",
  "pdf.cl.s7.b5": "Cliquez sur le bouton 'Acceder con Certificado Digital'.",
  "pdf.cl.s7.b6": "Votre navigateur vous demandera de choisir un certificat. Sélectionnez celui du propriétaire du bien.",
  "pdf.cl.s7.b7": "Un formulaire s'ouvre. La plupart des champs se remplissent depuis votre certificat. Renseignez le reste à partir de votre dossier.",
  "pdf.cl.s7.dept_title": "TRÈS IMPORTANT — choisissez le bon département",
  "pdf.cl.s7.dept_body": "Il y a une liste déroulante appelée 'Delegación'. Vous devez choisir LICENCIAS. PAS 'urbanismo'. PAS 'obras'. PAS 'proyectos'. Uniquement LICENCIAS. Si vous choisissez le mauvais, votre dossier va dans le mauvais service et est ignoré.",
  "pdf.cl.s7.attach": "Joignez ensuite TOUS ces fichiers (cochez chacun d'eux) :",
  "pdf.cl.s7.fd1": "Le formulaire signé (de l'étape 1)",
  "pdf.cl.s7.fd2": "Le PDF du récapitulatif des coûts (de l'étape 2)",
  "pdf.cl.s7.fd3": "Le PDF du plan cadastral (de l'étape 2)",
  "pdf.cl.s7.fd4": "Votre copie de passeport / NIE / DNI (de l'étape 2)",
  "pdf.cl.s7.fd5": "Le reçu bancaire de l'étape 4 (premier paiement)",
  "pdf.cl.s7.fd6": "La première facture de la mairie (de l'étape 3)",
  "pdf.cl.s7.fd7": "Le reçu bancaire de l'étape 5 (caution)",
  "pdf.cl.s7.fd8": "La deuxième facture de la mairie (de l'étape 6)",
  "pdf.cl.s7.fd_company1": "Les escrituras de la société (de l'étape 2)",
  "pdf.cl.s7.fd_company2": "Le certificat CIF de la société (de l'étape 2)",
  "pdf.cl.s7.submit": "Cliquez sur 'Presentar' (Envoyer) en bas de page.",
  "pdf.cl.s7.proof_title": "Conservez la preuve",
  "pdf.cl.s7.proof_body": "Après avoir cliqué sur Envoyer, le site vous affiche un petit PDF appelé 'acuse de recibo' ou 'justificante'. Il comporte un long numéro de reçu. ENREGISTREZ CE PDF. C'est votre preuve légale de dépôt. Vous pouvez légalement commencer les travaux dès que vous le voyez.",
  "pdf.cl.s7.youre_done": "Voilà. C'est terminé.",
  "pdf.cl.tr.header": "En cas de problème",
  "pdf.cl.tr.h1": "La mairie n'a pas répondu à votre premier courriel",
  "pdf.cl.tr.b1": "S'il s'est écoulé plus de 10 jours ouvrables (2 semaines) depuis l'envoi du courriel à l'étape 3, répondez à votre propre courriel pour qu'il remonte en haut de leur messagerie. Rédigez un court message poli en espagnol : 'Buenos días, le escribo de nuevo para solicitar la carta de pago. Gracias.' Si vous n'avez toujours pas de réponse au bout d'une semaine supplémentaire, appelez-nous.",
  "pdf.cl.tr.h2": "La mairie vous demande des documents supplémentaires",
  "pdf.cl.tr.b2": "C'est ce qu'on appelle un 'requerimiento'. Lisez ce qu'ils demandent. Envoyez uniquement ce qu'ils requièrent. Ne discutez pas. N'envoyez pas de documents non demandés. Vous n'avez QU'UNE SEULE chance de corriger les choses — ne la gâchez pas.",
  "pdf.cl.tr.h3": "La mairie vous indique qu'un projet d'architecte est nécessaire",
  "pdf.cl.tr.b3": "Cela signifie que les travaux dépassent ce que notre assistant peut gérer. Écrivez-nous à hello@marbellapermits.com — nous vous mettrons en contact avec un architecte partenaire à un tarif raisonnable.",
  "pdf.cl.tr.h4": "Vous avez choisi la mauvaise 'Delegación' à l'étape 7",
  "pdf.cl.tr.b4": "Cela arrive. Ne paniquez pas. Déposez une nouvelle instancia (recommencez l'étape 7), en choisissant cette fois LICENCIAS. Joignez une courte note indiquant 'Reemite el expediente — anterior presentado en Delegación incorrecta'. Les deux seront dans le système ; la mauvaise sera classée sans suite.",
  "pdf.cl.tr.closing": "Si quelque chose se produit qui n'est pas mentionné sur cette page : {help}",
  "pdf.cl.gl.header": "Vocabulaire utile",
  "pdf.cl.gl.title": "Termes espagnols que vous verrez — leur signification",
  "pdf.cl.gl.intro": "La mairie utilise des termes administratifs espagnols. Voici ce qu'ils signifient concrètement. Gardez cette page à portée de main.",
  "pdf.cl.gl.ayuntamiento": "Mairie.",
  "pdf.cl.gl.dr": "Le formulaire officiel que vous signez pour déclarer que vous allez réaliser des travaux. Parfois abrégé en 'DR'.",
  "pdf.cl.gl.carta_pago": "Une facture (en PDF) envoyée par la mairie. Il y en a deux — une pour la taxe de licence, une pour la caution.",
  "pdf.cl.gl.sede": "Le portail en ligne de la mairie. C'est là que vous téléversez le dossier final à l'étape 7.",
  "pdf.cl.gl.justificante": "Le reçu que vous donne votre banque après un paiement.",
  "pdf.cl.gl.acuse": "Le reçu numérique que le portail en ligne vous délivre APRÈS avoir cliqué sur Envoyer. C'est votre preuve légale.",
  "pdf.cl.gl.fianza": "Caution remboursable pour les déchets de chantier. Vous la récupérez à la fin des travaux.",
  "pdf.cl.gl.presupuesto": "Récapitulatif des coûts des travaux, hors TVA, en espagnol.",
  "pdf.cl.gl.plano": "Un plan de votre bien. Vous le téléchargez gratuitement sur le site du cadastre espagnol.",
  "pdf.cl.gl.nie": "Le numéro d'identification espagnol pour les étrangers. Obligatoire si le propriétaire du bien n'est pas de nationalité espagnole.",
  "pdf.cl.gl.subsanacion": "Correction des erreurs dans votre dossier. Vous n'avez qu'une seule chance.",
  "pdf.cl.gl.requerimiento": "Un courrier de la mairie demandant des documents supplémentaires ou des précisions. Signifie qu'une subsanación est nécessaire.",
  "pdf.cl.gl.tramite": "Une démarche administrative. L'ensemble de la procédure de permis est un trámite.",
  "pdf.cl.gl.delegacion": "Un département de la mairie. Il y en a plusieurs — assurez-vous de choisir LICENCIAS à l'étape 7.",
  "pdf.cl.gl.pem": "Coût des travaux, hors TVA (le même chiffre que nous vous avons demandé dans l'assistant).",
  "pdf.cl.gl.icio": "La taxe sur les travaux de construction. Environ 3,5% du PEM. Incluse dans la première facture.",
  "pdf.cl.gl.visado": "Le cachet de validation d'un projet d'architecte. Uniquement nécessaire pour des travaux plus importants — ce n'est pas votre cas.",
  "pdf.email.title": "Courriel à copier et envoyer",
  "pdf.email.body_label": "Corps — à copier mot pour mot",
  "pdf.email.before_title": "Avant d'envoyer",
  "pdf.email.before_body": "Joignez les documents justificatifs listés à l'étape 2 du guide d'instructions (fichier 00). Vérifiez que toutes les pièces jointes sont en PDF, clairement nommées, et font moins de 10 Mo chacune.",
  "pdf.email.license_header": "03 · Premier courriel — à la mairie (oficinaliquidadora)",
  "pdf.email.license_instr": "Ouvrez votre programme de messagerie. Collez les lignes À, Objet et Corps ci-dessous. Joignez les documents de l'étape 2 du guide d'instructions.",
  "pdf.email.waste_header": "04 · Deuxième courriel — à la mairie (caja)",
  "pdf.email.waste_instr": "Envoyez ce courriel APRÈS avoir payé la caution remboursable (étape 5 du guide d'instructions). Joignez le reçu bancaire.",
  "pdf.carta.when_title": "Quand utiliser ce document",
  "pdf.carta.when_body": "Uniquement si vous souhaitez qu'une autre personne (un gestionnaire de propriété, un gestor ou un avocat) dépose la Declaración Responsable en votre nom via la sede electrónica espagnole. Cette personne devra joindre cette lettre signée par vous.",
  "pdf.carta.brackets_title": "Les crochets surlignés sont des espaces réservés",
  "pdf.carta.brackets_body": "Remplacez [Nombre del representante autorizado] et [NIE/DNI del representante] par les coordonnées réelles de la personne que vous autorisez. Imprimez, signez, scannez.",
  "pdf.presu.note_title": "Note architecte / propriétaire",
  "pdf.presu.note_body": "Si votre dossier nécessite un détail par partidas et capítulos (movimiento de tierras, estructura, etc.), ajoutez-le en annexe. Pour les travaux de Section A, ce récapitulatif en une ligne est généralement accepté.",
  "pdf.eg.header": "02 · Ce qu'il faut conserver",
  "pdf.eg.eyebrow": "Guide dans votre langue",
  "pdf.eg.title": "Vos travaux sont exemptés. Voici ce qu'il faut faire ensuite.",
  "pdf.eg.intro": "En vertu de l'instrucción urbanística de Marbella de janvier 2026, les travaux simples de moins de €10 000 — peinture, finitions, certaines installations intérieures — n'ont pas besoin de permis. Vous pouvez commencer demain. Mais il reste quelques démarches à effectuer pour vous protéger.",
  "pdf.eg.keep_title": "Conservez ces documents",
  "pdf.eg.keep1": "Le PDF d'auto-certification signé (fichier 01)",
  "pdf.eg.keep2": "Une facture détaillée de l'entrepreneur indiquant le coût total",
  "pdf.eg.keep3": "Des photos avant / après des travaux",
  "pdf.eg.keep4": "Les reçus de toute élimination de déchets",
  "pdf.eg.complaint_title": "Si un voisin se plaint",
  "pdf.eg.complaint_body": "La mairie peut tout de même inspecter même lorsque les travaux sont exemptés. Si elle vous le demande, remettez-lui : l'auto-certification (fichier 01), la facture de l'entrepreneur et les photos. L'inspection confirme que les travaux entrent dans la catégorie exemptée. Aucune sanction ne s'applique si votre périmètre correspond à la déclaration.",
  "pdf.eg.stops_title": "Quand l'exemption cesse de s'appliquer",
  "pdf.eg.stops_callout_title": "Passez à une Declaración Responsable si l'une de ces situations se présente",
  "pdf.eg.stops_callout_body": "Le budget dépasse €10 000. Tout déplacement de mur. Toute nouvelle ouverture dans la façade. Tout travail de plomberie ou d'électricité affectant les installations communes. Le bien est ou devient situé dans une zone de protection historique.",
  "pdf.eg.stops_body": "Dans l'un de ces cas, revenez sur marbellapermits.com et relancez l'assistant. Nous préparerons un dossier DR complet pour vous.",
  "pdf.eg.resale_title": "Diligence raisonnable lors de la revente",
  "pdf.eg.resale_body": "Lorsque vous vendrez le bien, le notaire ou l'avocat de l'acheteur pourra vous demander si des travaux de rénovation ont été réalisés et s'ils ont été autorisés. Remettez-leur cette auto-certification — elle montre que les travaux étaient légalement exemptés, avec la référence réglementaire. C'est exactement ce dont ils ont besoin pour valider la diligence raisonnable.",
  "pdf.eg.footer": "02 · Ce qu'il faut conserver · Marbella Permits",
  "wiz.help.panel_title": "Bloqué à une étape ? Ouvrez l’aide pas à pas",
  "wiz.help.intro": "Cliquez sur une étape pour l’ouvrir. C’est le même guide que votre PDF téléchargé — utilisez celui que vous préférez. Si vous êtes toujours bloqué après lecture, appelez-nous ou écrivez-nous.",
  "wiz.help.ask": "Une question sur votre permis"
});
}
